Zora
reservoirprotocol/indexer pull request #1395
Opened 2022-08-04 15:30 UTC by diegoramosxyz

2022-08-06 06:05 UTC, georgeroman requested changes

2022-08-06 06:05 UTC, georgeroman commented on src/sync/events/data/zora.ts
> +  addresses: { [Zora.Addresses.Exchange[config.chainId].toLowerCase()]: true },
Let's change this to `Zora.Addresses.Exchange[config.chainId]?.toLowerCase()` otherwise instances for which there is no defined exchange contract will error.

2022-08-06 06:05 UTC, georgeroman commented on src/sync/events/index.ts
> +              if (![Sdk.Common.Addresses.Weth[config.chainId], AddressZero].includes(askCurrency)) {
Should be consistent here and use `Sdk.Common.Addresses.Eth[config.chainId]` instead of `AddressZero`.

2022-08-06 06:05 UTC, georgeroman commented on src/sync/events/index.ts
> +                orderSide: "buy",
This is the `Asks` module, which implies listings and so the side should be 'sell'.

2022-08-06 06:05 UTC, georgeroman commented on src/sync/events/index.ts
> +              fillEventsPartial.push({
No need to use `fillEventsPartial` here, can use `fillEvents`.

2022-08-06 06:05 UTC, georgeroman commented on src/migrations/1659625683558_zora-order-kind.sql
> +ALTER TYPE "order_kind_t" ADD VALUE 'zora';
Let's use `zora-v3` for the name.

2022-08-06 06:07 UTC, georgeroman commented
Also, might need to rebase your branch on `v5` and incorporate some of the latest changes there like handling attribution and setting the correct prices in ETH and USD.

2022-08-06 06:09 UTC, georgeroman commented
Also, let's handle `zora-v3` as a default source: https://github.com/reservoirprotocol/indexer/blob/5eb39ce3ca4b3cd076f1935349c28d820513a838/src/sync/events/utils.ts#L103-L124

2022-08-15 06:18 UTC, georgeroman commented
We recently added support for handling sales in ERC20 tokens (anything other than ETH/WETH), so let's also make sure we properly handle those here. You can see here an example on how to deal with it: https://github.com/reservoirprotocol/indexer/blob/562724971a658d8faaca53e0382de2dd2d08e9cd/src/sync/events/index.ts#L610-L636.

2022-08-15 18:18 UTC, diegoramosxyz commented
@georgeroman Why do you have a check for WETH and ETH here:

https://github.com/reservoirprotocol/indexer/blob/562724971a658d8faaca53e0382de2dd2d08e9cd/src/sync/events/index.ts#L560-L568

Isn't the `getPrices` function already making this check? Wouldn't this check nullify checks for other ERC20s?

2022-08-16 12:03 UTC, georgeroman commented
Looks good, let's resolve the conflicts and should be good to merge.

2022-08-16 15:31 UTC, merged