Cryptopunks
reservoirprotocol/indexer pull request #1398
Opened 2022-08-04 18:55 UTC by diegoramosxyz

2022-08-06 06:14 UTC, georgeroman commented
The punks market might require some hacks due to this issue: https://github.com/larvalabs/cryptopunks/issues/19. We basically need to index their `Transfer` events as well in order to correctly set the bugged field on the `PunkBought` event. We should also handle the punks market as a default source and update the pricing (check the comments on the zora PR).

2022-08-11 05:57 UTC, ptrwtts commented
We should probably set the source to `cryptopunks.app`, which is the new domain for the marketplace since Yuga bought it.

2022-08-15 06:29 UTC, georgeroman requested changes

2022-08-15 06:29 UTC, georgeroman commented on src/sync/events/index.ts
> +              nftTransferEvents.push({
For the moment, let's not save these transfer events in the database.

2022-08-15 06:29 UTC, georgeroman commented on src/sync/events/index.ts
> +            case "cryptopunks-transfer": {
Simply indexing the transfer events is not going to fix our problem, we need to use the transfer event for properly setting the `toAddress`. Also, since the `value` filled is bugged as well, we need to find a way to properly set that as well (a quick workaround would be to parse the `minPrice` parameter from the calldata and use that as the price. We do similar processing for handling wyvern sales, so can use that code as an example: https://github.com/reservoirprotocol/indexer/blob/562724971a658d8faaca53e0382de2dd2d08e9cd/src/sync/events/index.ts#L1077-L1106

2022-08-19 16:06 UTC, georgeroman requested changes

2022-08-19 16:06 UTC, georgeroman commented on src/sync/events/index.ts
> +              cryptopunksTransferEvents.push({
We only care about `to` and `txHash`, let's only store these.

2022-08-19 16:06 UTC, georgeroman commented on src/sync/events/index.ts
> +                contract: Sdk.CryptoPunks.Addresses.Exchange[config.chainId]?.toLowerCase(),
Let's use `baseEventParams.address`.

2022-08-19 16:06 UTC, georgeroman commented on src/sync/events/index.ts
> +                currency: AddressZero,
Let's use the `Sdk.Common.Addresses.Eth[config.chainId]`.

2022-08-19 16:06 UTC, georgeroman commented on src/sync/events/index.ts
> +                orderSide: "buy",
The order side could also be `sell`, we can actually use a little hack and depending on the `toAddress` (whether it's `0x00.0..000` or not) set the side to `buy` or `sell` (eg. `buy` if it is the zero address, `sell` otherwise).

2022-08-19 16:06 UTC, georgeroman commented on src/sync/events/index.ts
> +              if (
Let's maybe add some comments explaining why we do these hacks the way we do them.

2022-08-22 13:19 UTC, georgeroman commented on src/sync/events/index.ts
> +              const orderSide = toAddress === AddressZero ? "buy" : "sell";
This is not going to work since we already fix the zero address issue above. We should have this line before we make the fix.

2022-08-22 13:20 UTC, georgeroman commented on src/sync/events/index.ts
> +              if (!prices.nativePrice) break;
Let's add `{ ... }` for consistency with the rest of the codebase.

2022-08-22 14:44 UTC, closed without merging