feat: remove burned tokens from stats
reservoirprotocol/indexer pull request #1455
Opened 2022-08-15 00:11 UTC by jrfrantz

This PR attempts to remove burned tokens (eg owned by `address(0)`) from the stats endpoint. I don't know how to test this locally so let me know if it looks off and happy to change whatever.

Discussion in discord was to remove burned tokens from stats but leave in other tokens endpoints (where they can be more easily removed on client). Link: https://discord.com/channels/872790973309153280/1007323955574603847/1007631754103898132

2022-08-17 13:24 UTC, georgeroman requested changes

2022-08-17 13:24 UTC, georgeroman commented on src/api/endpoints/stats/get-stats/v1.ts
> +            WHERE "owner" = ${toBuffer(AddressZero)}
String interpolation is not going to work, we need to have a new query param (eg. `burnAddress`) and set that to `toBuffer(AddressZero)` in the query params object.

2022-08-17 13:24 UTC, georgeroman commented on src/api/endpoints/stats/get-stats/v1.ts
> +            "c"."token_count" - (SELECT COUNT(*) FROM "burned") AS "token_count",
No need for the `WITH` clause, could just have something like `(SELECT COUNT(*) FROM nft_balances WHERE contract = ... AND owner = ... AND amount > 0)`.

2023-03-09 17:27 UTC, nofir commented
closing due to lack of activity

2023-03-09 17:27 UTC, closed without merging