feat: universe - base implementation
reservoirprotocol/indexer pull request #1904
Opened 2022-09-20 06:36 UTC by vikinatora

2022-09-26 12:58 UTC, georgeroman requested changes

2022-09-26 12:58 UTC, georgeroman commented on src/api/endpoints/execute/get-execute-bid/v4.ts
> +            if (!["universe"].includes(params.orderbook)) {
Do we want to allow posting directly to `reservoir` as well?

2022-09-26 12:58 UTC, georgeroman commented on src/api/endpoints/execute/get-execute-list/v4.ts
> +          // eslint-disable-next-line no-fallthrough
I think we're missing the `continue` on the above case.

2022-09-26 12:58 UTC, georgeroman commented on src/api/endpoints/execute/get-execute-sell/v4.ts
> +          // TODO: Ask George, how we can support APE coin?
On mainnet for listings APE coin will be supported by default (as long as the SDK code supports listing in ERC20) - no need to do any special handling for it.

2022-09-26 12:58 UTC, georgeroman commented on src/api/endpoints/execute/get-execute-bid/v4.ts
> +        //TODO: Add support for more ERC20 tokens
We do have in plan bids in non-WETH tokens (probably USDC at first) - unfortunately due to how the indexer works (eg. it needs to have the full balance of every owner for properly validating the orders) we need an extra backfill for every ERC20 token we support on the bid side.

2022-09-26 12:58 UTC, georgeroman commented on src/api/endpoints/execute/get-execute-buy/v4.ts
> +        if (!listingDetails.every((d) => d.kind === "seaport" || d.kind === "universe")) {
I think we either want all `seaport` or all `universe`. If everything is `seaport` then we keep the code below which gets the conduit, otherwise we need the conduit to be the universe exchange address (or whatever contract we need the approval on).

2022-09-26 12:58 UTC, georgeroman commented on src/api/endpoints/execute/get-execute-list/v4.ts
> +              throw Boom.badRequest("Only `reservoir` is supported as orderbook");
Given the if condition, should this be `universe`? Also, see the comment above on allowing `reservoir` as well.

2022-09-26 12:58 UTC, georgeroman commented on src/orderbook/orders/universe/check.ts
> +    //TODO: Not sure if this will work. Ask George@Reservoir?
This should work, but probably better to rename `filled` to `amount` or something that better denotes that it's the total quantity the order was intended for.

2022-09-26 12:58 UTC, georgeroman commented on src/sync/events/handlers/universe.ts
> +        const orderKind = eventData.kind.startsWith("universe") ? "universe" : "";
No need for the `? :` here, we can just set `orderKind = "universe"` directly.

2022-09-26 12:58 UTC, georgeroman commented on src/sync/events/index.ts
> +        kind: "universe",
Since we're already handling `universe` in its own handler file, let's remove it from above (and only keep `rarible-match`).

2022-09-26 13:49 UTC, vikinatora commented on src/api/endpoints/execute/get-execute-bid/v4.ts
> +            if (!["universe"].includes(params.orderbook)) {
I will talk with the PO about this.

2022-09-26 13:51 UTC, vikinatora commented on src/api/endpoints/execute/get-execute-list/v4.ts
> +              throw Boom.badRequest("Only `reservoir` is supported as orderbook");
I'll talk to the PO about this

2022-09-26 14:22 UTC, vikinatora commented on src/api/endpoints/execute/get-execute-list/v4.ts
> +              throw Boom.badRequest("Only `reservoir` is supported as orderbook");
If we allow `reservoir`, the fees that our contract honours and that are set in the order itself will be persisted right?

2022-09-27 10:40 UTC, georgeroman commented on package.json
> -    "@reservoir0x/sdk": "0.0.182",
Let's `yarn add @reservoir0x/sdk@0.0.183` so that `yarn.lock` gets updated as well.

2022-09-27 10:44 UTC, merged