feat: support element
reservoirprotocol/indexer pull request #2142
Opened 2022-10-25 04:15 UTC by lljxx1

- add element
- `bulkCancelEvents` add support to cancle all the maker's related orders
- integration tests cover `sellERC721` `buyERC721` `sellERC1155` `buyERC1155` `cancelOrder` `incrementHashNonce`

2022-10-25 06:06 UTC, georgeroman requested changes
We don't need to create Element orders, so let's remove any logic in `/execute/bid`, `/execute/list` and `POST /order` (also in `/orders/element/build`). We should probably support element in `POST /orders/` (since that's what the relayer uses).

2022-10-25 06:06 UTC, georgeroman commented on src/orderbook/orders/element/index.ts
> +      // Check: order has unique nonce
Since the Element filling events include the order's hash there is no need to have this restriction here. This is only relevant for ZeroExV4 which doesn't include the order's hash in the fill event and so we had to have some uniqueness restrictions in order to know which order to mark as filled.

2022-10-25 06:06 UTC, georgeroman commented on src/orderbook/orders/element/index.ts
> +        case "token-range": {
No need to support `token-range` and `token-list-*`, since Element only supports `single-token` and `contract-wide`.

2022-10-25 06:06 UTC, georgeroman commented on src/orderbook/orders/element/index.ts
> +      // const timestamp = BigNumber.from(order.params.expiry).and(BigNumber.from("0xffffffff")).toString();
Should remove this

2022-10-25 06:06 UTC, georgeroman commented on src/orderbook/orders/element/index.ts
> +        quantity_remaining: order.params.nftAmount,
Will this work for ERC721 as well? We want a default of 1 in this case.

2022-10-25 06:06 UTC, georgeroman commented on src/orderbook/orders/element/index.ts
> +    // if (relayToArweave) {
Should enable this?

2022-10-25 06:33 UTC, lljxx1 commented on src/sync/events/storage/bulk-cancel-events.ts
> +      ${acrossAll ? `` : `AND "o"."nonce" < "x"."min_nonce" `}
yeah, currently there has two kind of nonce: 
- order-level 
- account-level 

the order's nonce in database is order-level.
when account-level nonce increase, cannot use `nonce < min nonce` to cancel all

2022-10-25 06:42 UTC, lljxx1 commented on src/sync/events/storage/bulk-cancel-events.ts
> +      ${acrossAll ? `` : `AND "o"."nonce" < "x"."min_nonce" `}
@georgeroman That's why I need to remove the `nonce < main nonce` condition

2022-10-25 08:52 UTC, georgeroman commented on src/api/endpoints/orders/post-order/v2.ts
> +f;
Let's remove this and should be good to go on dev

2022-10-26 06:24 UTC, georgeroman commented on src/orderbook/orders/element/index.ts
> +      const isReservoir = true;
This should be false.

2022-10-26 07:41 UTC, merged