Manifold
reservoirprotocol/indexer pull request #2438
Opened 2022-11-28 13:02 UTC by boris-bonin

Initial indexer implementation that support cancel, purchase, finalize and modify  event ingestion.

Manifold is an on-chain escrowed orderbook.

2022-11-28 13:08 UTC, vikinatora commented
The only sell events that we're not indexing right now are ranked auction and dynamic price listing. The issue with them are that token transfer and nft delivery is done in collect and deliver function. These functions don't emit any exchange specific events and it's hard to track. This is not an issue in my opinion as there's not been such orders created on Manifold. Check https://marketplace.api.manifoldxyz.dev/listing/0x3a3548e060be10c2614d0a4cb0c03cc9093fd799/activity?sortAscending=true&pageNumber=1&pageSize=2000&type=2 the two order types that we don't support are `type_: 3` and `type_: 4`.

2022-11-28 14:26 UTC, georgeroman requested changes

2022-11-28 14:26 UTC, georgeroman commented on src/sync/events/handlers/manifold.ts
> +import { BigNumber } from "ethers";
Let's use the `bn` method instead.

2022-11-28 14:26 UTC, georgeroman commented on src/sync/events/handlers/manifold.ts
> +    if (call.type === "CALL" && call.from === eventParams.address && call.value !== "0x0") {
Hmm, what's the idea behind the `call.from === eventParams.address` check?

2022-11-28 14:26 UTC, georgeroman commented on src/sync/events/handlers/manifold.ts
> +            // Event data doesn't include full transaction information so we have to parse the calldata
Same here, better if we could use call tracing for everything instead.

2022-11-28 14:33 UTC, vikinatora commented on src/sync/events/handlers/manifold.ts
> +    if (call.type === "CALL" && call.from === eventParams.address && call.value !== "0x0") {
Maybe `call.from === eventParams.address` isn't necessary but since ETH transfer always have the exchange contract as `from` I decided to add that as additional condition

2022-11-28 14:35 UTC, vikinatora commented on src/sync/events/handlers/manifold.ts
> +            currencyPrice = amount;
We do that here: https://github.com/reservoirprotocol/indexer/pull/2438/files#diff-3d80e2d160235555d4301cf1d94e6249ff4b3fc9442ec55720808dd58e8a5f2aR342

2022-12-02 14:31 UTC, georgeroman requested changes

2022-12-02 14:31 UTC, georgeroman commented on src/jobs/orderbook/orders-queue.ts
> -            logger.info(QUEUE_NAME, `[rarible] Order save result: ${JSON.stringify(result)}`);
Let's leave the log, and also include it for Manifold orders.

2022-12-02 14:31 UTC, georgeroman commented on src/orderbook/orders/manifold/index.ts
> +        currency: toBuffer(orderParams.details.erc20),
Let's just ignore any non-ETH orders.

2022-12-02 14:31 UTC, georgeroman commented on src/orderbook/orders/manifold/index.ts
> +        conduit: toBuffer(Sdk.Manifold.Addresses.Exchange[config.chainId]),
Let's set the conduit to `null` since it's not relevant for escrowed orderbooks.

2022-12-02 14:31 UTC, georgeroman commented on src/sync/events/handlers/manifold.ts
> +          break;
If we're skipping sales for which we don't have the order it means that we won't have historical sales, which we want. Any fields extracted from the order data can probably be retrieved from the call trace.

2022-12-02 14:45 UTC, georgeroman commented on src/orderbook/orders/manifold/index.ts
> +
Should we also ensure here the listing is a fixed-price one (eg. type = 2)?

2022-12-03 10:14 UTC, georgeroman requested changes
One additional change we might want to make is make sure to trigger an `orderUpdatesById` for in-place order updates (and not just for new orders). Check out these changes: https://github.com/reservoirprotocol/indexer/pull/2513/files.

2022-12-05 16:11 UTC, georgeroman commented on src/orderbook/orders/manifold/index.ts
> +    await ordersUpdateById.addToQueue(
We should move this outside of the if statement, otherwise we'll only trigger events if the current batch contains new orders (which might not be the case at all times).

2022-12-05 16:22 UTC, georgeroman commented on src/orderbook/orders/manifold/check.ts
> +  // Indexer specififc validations
Indexer-specific validations should go into the `index.ts` file (in the `save` method).

2022-12-05 16:23 UTC, georgeroman commented on src/orderbook/orders/manifold/check.ts
> +  if (order.details.erc20 !== constants.AddressZero) {
Should use `Sdk.Common.Addresses.Eth` instead of `AddressZero`.

2022-12-05 17:41 UTC, georgeroman commented on src/sync/events/handlers/manifold.ts
> +          break;
I'm worried about historical listings which might not get ingested if we have this check. Maybe we can assume that the maker is the recipient of the highest ETH/ERC20 payment part of the purchase (sub)transaction. What do you think?

2022-12-06 08:28 UTC, vikinatora commented on src/sync/events/handlers/manifold.ts
> +        if (orderResult && orderResult.valid_from === 0) {
This should stay as it's applicable only to active orders.

2022-12-06 08:34 UTC, merged