Infinity
reservoirprotocol/indexer pull request #2470
Opened 2022-11-29 19:14 UTC by jfrazier-eth

2022-12-16 13:24 UTC, georgeroman requested changes
Let's remove `package-lock.json`

2022-12-16 13:24 UTC, georgeroman commented on src/orderbook/orders/index.ts
> +        return sources.getOrInsert("infinity.xyz"); // TODO - what needs to be done to add infinity to source? do I update the json file?
No need to do anything, we'll fetch all details from the domain automatically. Can manually tweak anything afterwards. Let's remove the comment.

2022-12-16 13:24 UTC, georgeroman commented on src/orderbook/orders/infinity/build/buy/collection.ts
> +import * as utils from "../utils";
Not a big deal, but we usually use full path imports: `@/orderbook/orders/infinity/build/utils`.

2022-12-16 13:24 UTC, georgeroman commented on src/orderbook/orders/infinity/build/buy/token.ts
> +import * as utils from "../utils";
Same comment as above for the full path import.

2022-12-16 13:24 UTC, georgeroman commented on src/orderbook/orders/infinity/build/sell/token.ts
> +import * as utils from "../utils";
Same here.

2022-12-16 13:24 UTC, georgeroman commented on src/orderbook/orders/infinity/build/utils.ts
> +  maxGasPrice?: number;
Interesting, is this an order parameter?

2022-12-16 13:24 UTC, georgeroman commented on src/orderbook/orders/infinity/check.ts
> +    if (!kind) {
Simpler to use `kind !== "erc721"`?

2022-12-16 13:24 UTC, georgeroman commented on src/orderbook/orders/infinity/index.ts
> +
Let's maybe add a check here to ensure the order only applies to a single NFT, eg. `order.nfts.length === 1`.

2022-12-16 13:24 UTC, georgeroman commented on src/sync/events/handlers/infinity.ts
> +        for (const nft of nfts) {
Are orders with multiple tokens bundles? If so we should probably exclude them for the fill events (at least for now) since it doesn't make sense to split the price across all tokens in a bundle.

2022-12-16 13:24 UTC, georgeroman commented on src/orderbook/orders/infinity/index.ts
> +
We should also make sure to only support ETH listings and WETH bids.

2022-12-16 13:24 UTC, georgeroman commented on src/sync/events/handlers/infinity.ts
> +  const sellerOrderNonce = await getOrderNonce(orderHash, seller);
What would happen if we don't have the order in our system so we can't cancel the nonce but then we receive an order with the nonce that was cancelled via filling? We should probably use call tracing (check the sudoswap / blur sales handling) to always get the nonce (I assume it's available in the calldata).

2022-12-16 15:52 UTC, jfrazier-eth commented on src/orderbook/orders/infinity/index.ts
> +
What is the reasoning for adding this here? To prevent the `offChainCheck` from happening?

2022-12-16 15:52 UTC, jfrazier-eth commented on src/orderbook/orders/infinity/build/utils.ts
> +  maxGasPrice?: number;
Yes, when orders are executed by our matching engine our exchange takes refund from the buyer to pay for any gas used. The max gas price can be set so that they can control the max gas price that their order will be executed at.

2022-12-16 15:53 UTC, jfrazier-eth commented on src/orderbook/orders/infinity/build/buy/collection.ts
> +import * as utils from "../utils";
Will do, would you like me to add a `.vscode/settings.json` with the setting below to make this the default for vscode auto imports?
```
{
  "typescript.preferences.importModuleSpecifier": "non-relative"
}
```

2022-12-16 15:53 UTC, jfrazier-eth commented on src/orderbook/orders/index.ts
> +        return sources.getOrInsert("infinity.xyz"); // TODO - what needs to be done to add infinity to source? do I update the json file?
Great

2022-12-16 15:58 UTC, jfrazier-eth commented on src/sync/events/handlers/infinity.ts
> +        for (const nft of nfts) {
Okay, does this include fill info events? i.e. should we exclude both fill events and fill info events for bundles?

2022-12-16 16:11 UTC, georgeroman commented on src/orderbook/orders/infinity/index.ts
> +
Yes, just to return as early as possible.

2022-12-16 16:12 UTC, georgeroman commented on src/sync/events/handlers/infinity.ts
> +        for (const nft of nfts) {
Yes, since it can be misleading to split the price across all items in the bundle, eg. a bundle of one bored ape and one worthless token selling at 100ETH would split the price across the two, when in reality one token was more expensive than the other.

2022-12-16 19:39 UTC, jfrazier-eth commented on src/sync/events/handlers/infinity.ts
> +  const sellerOrderNonce = await getOrderNonce(orderHash, seller);
Good catch, I added parsing the nonce from the calldata

2022-12-21 12:13 UTC, georgeroman requested changes

2022-12-21 12:13 UTC, georgeroman commented on src/orderbook/orders/infinity/index.ts
> +        conduit: null,
The conduit should be the contract on which approvals are given, required because that's how we are going to validate/invalidate orders given approval changes.

2022-12-21 12:15 UTC, georgeroman commented on src/orderbook/orders/infinity/index.ts
> +        contract: null,
The contract should also be set to the contract the order applies to (we don't support any type of cross-contract orders at the moment).

2022-12-21 16:20 UTC, jfrazier-eth commented on src/orderbook/orders/infinity/index.ts
> +        contract: toBuffer(Sdk.Infinity.Addresses.Exchange[config.chainId]),
Ahh, will change this

2022-12-27 09:09 UTC, merged