Feat: consecutive transfers
reservoirprotocol/indexer pull request #2480
Opened 2022-12-01 08:33 UTC by vikinatora

Added event hander for erc721 consescutive transfers. The processing is almost identical to erc721 single transfers. The event handler logic for both events can be extracted in a function but decided to not go for that since their handling should be independent of one another.

2022-12-02 14:18 UTC, georgeroman requested changes

2022-12-02 14:18 UTC, georgeroman commented on src/sync/events/handlers/erc721.ts
> -          context: `${contextPrefix}-${to}-sell-balance`,
Just realized that this is actually not a duplicate, it has a different context (using `to` instead of `from`).

2022-12-02 14:18 UTC, georgeroman commented on src/sync/events/handlers/erc721.ts
> +            context: `${contextPrefix}-${from}-sell-balance`,
We need a similar `makerInfo` struct for the `to` address, as mentioned above regarding the duplicate.

2022-12-02 14:20 UTC, georgeroman requested changes

2022-12-02 14:20 UTC, georgeroman commented on src/sync/events/handlers/erc721.ts
> +        for (let i = fromTokenId; i <= toTokenId; i++) {
Since `fromTokenId` and `toTokenId` are `string`s, incrementing will not work I think. What you could do instead is wrap the `for` loop in a `try`/`catch` and convert to `number`.

2022-12-05 07:38 UTC, vikinatora commented on src/sync/events/handlers/erc721.ts
> +        for (let i = fromTokenId; i <= toTokenId; i++) {
Converting strings works implicitly. I've tested it in multiple scenarios. However I agree that the iterators should work with `number` instead of `string`

2022-12-05 07:43 UTC, vikinatora commented
@georgeroman Ready for re-review

2022-12-05 08:17 UTC, merged