feat: seaport royalties
reservoirprotocol/indexer pull request #2505
Opened 2022-12-02 14:58 UTC by lljxx1

2022-12-02 16:12 UTC, georgeroman requested changes

2022-12-02 16:12 UTC, georgeroman commented on src/sync/events/storage/fill-events/index.ts
> +  royalty_fee_bps?: number;
We should use camelCase for the `Event` type.

2022-12-02 16:17 UTC, georgeroman requested changes

2022-12-02 16:17 UTC, georgeroman commented on src/sync/events/handlers/royalties/index.ts
> +  royalty_fee_bps: number;
Let's use camelCase.

2022-12-02 16:17 UTC, georgeroman commented on src/sync/events/handlers/royalties/seaport.ts
> +  const royalty_fee_breakdown: Royalty[] = [];
Let's use camelCase.

2022-12-02 16:17 UTC, georgeroman commented on src/sync/events/handlers/royalties/seaport.ts
> +    const balanceChange = tokenBalanceState[native] || tokenBalanceState[weth];
Why only weth? Seaport does support any erc20.

2022-12-02 16:17 UTC, georgeroman commented on src/sync/events/handlers/royalties/seaport.ts
> +    royalty_fee_bps: getTotalRoyaltyBps(royalty_fee_breakdown),
Let's use camelCase.

2022-12-05 16:32 UTC, georgeroman requested changes

2022-12-06 01:33 UTC, lljxx1 commented on src/sync/events/handlers/royalties/seaport.ts
> +    const balanceChange = tokenBalanceState[native] || tokenBalanceState[weth];
Sorry, I forget to push this changes

2022-12-27 09:42 UTC, merged