Non standard tokens - Beeple and CryptoArte transfer handling
reservoirprotocol/indexer pull request #2551
Opened 2022-12-07 07:23 UTC by vikinatora

2022-12-09 13:38 UTC, georgeroman requested changes

2022-12-09 13:38 UTC, georgeroman commented on src/sync/events/storage/nft-transfer-events.ts
> +  kind:
Let's extract these to a high-level type `ContractKind`.

2022-12-09 13:38 UTC, georgeroman commented on src/migrations/1670318026167_add-cryptoarte-contract-kind.sql
> +ALTER TYPE "contract_kind_t" ADD VALUE 'cryptoarte';
Since all of these (including the previously added cryptokitties) have the same event signature I think we can bundle all together into a single contract kind `erc20-like` (since the event signature matches the ERC20 transfer signature).

2022-12-09 13:38 UTC, georgeroman commented on src/migrations/1670318026167_add-cryptoarte-contract-kind.sql
> +ALTER TYPE "contract_kind_t" ADD VALUE 'cryptoarte';
This should result in a single handler for all of these.

2022-12-09 13:38 UTC, georgeroman commented on src/migrations/1670318026167_add-cryptoarte-contract-kind.sql
> +ALTER TYPE "contract_kind_t" ADD VALUE 'cryptoarte';
So let's just rename `cryptokitties` to `erc20-like` (eg. https://stackoverflow.com/questions/12627830/rename-enum-item-in-postgresql).

2022-12-09 13:38 UTC, georgeroman commented on src/sync/events/handlers/index.ts
> +    case "cryptoarte": {
Once we have the `erc20-like` type, we should use the same handler as we do for `erc721`: https://github.com/reservoirprotocol/indexer/blob/cb747506c692db144323eab6824a4c7296c8e15a/src/sync/events/handlers/index.ts#L62
We should only make sure to handle it in the exact way as a `erc721-transfer`: https://github.com/reservoirprotocol/indexer/blob/cb747506c692db144323eab6824a4c7296c8e15a/src/sync/events/handlers/erc721.ts#L45

Something like:
```javascript
case "erc721-transfer":
case "erc20-like-transfer": {
   ...
}
```

2022-12-12 11:13 UTC, vikinatora commented on src/sync/events/data/erc721.ts
> +  },
I've added address constraint to the contract we know that emits such event. This is in order to prevent any erc20-like transfer being handled as erc721

2022-12-12 11:13 UTC, vikinatora commented on src/sync/events/data/erc721.ts
> +    [CryptoVoxels.Addresses.Parcel[config.chainId]?.toLowerCase()]: true,
Same reason as above

2022-12-12 14:32 UTC, georgeroman commented
Let's just remove the old migration files and should be good to go.

2022-12-12 14:45 UTC, vikinatora commented
Removed.

2022-12-16 12:51 UTC, merged