feat: order-saving support for nftx
reservoirprotocol/indexer pull request #2602
Opened 2022-12-12 08:46 UTC by lljxx1

2022-12-16 15:35 UTC, georgeroman commented on src/utils/nftx/index.ts
> +export async function getPoolNFTs(vault: string) {
To skip an expensive on-chain call, we should use the off-chain equivalent, as we do here: https://github.com/reservoirprotocol/indexer/blob/5f0527f66728e7620a1db4a2de576186bb0ff8d4/src/orderbook/orders/sudoswap/index.ts#L366

2022-12-23 09:44 UTC, georgeroman requested changes

2022-12-23 09:44 UTC, georgeroman commented on package.json
> +    "@reservoir0x/sdk": "^0.0.271",
Let's keep fixed versions, just for safety.

2022-12-23 09:44 UTC, georgeroman commented on src/utils/nftx/index.ts
> +    // && log.address.toLowerCase() === address
Let's remove this.

2022-12-23 09:44 UTC, georgeroman commented on src/sync/events/handlers/nftx.ts
> +        if (hasSwap) {
Shouldn't it be the other way around - if we have more than one swap we break?

2022-12-23 09:44 UTC, georgeroman commented on src/orderbook/orders/nftx/index.ts
> +      const poolPrice = await Sdk.Nftx.helpers.getPoolPrice(
We should assume the buyer always buys a single amount and then get a list of prices for buying each incrementing amount:
`[PriceToBuyQuantity1, PriceToBuyQuantity2, ...]`

2022-12-30 12:02 UTC, georgeroman commented on package.json
> +    "@reservoir0x/sdk": "^0.0.271",
This was not addressed yet.

2022-12-30 12:12 UTC, georgeroman requested changes
The below requirements (eg. having a single minted and swap event in the same transaction) were made in order to simplify sale detection logic. It would be very hard to get the price of a sale across multiple transactions. However, now that we're handling NFTX liquidity we cannot afford losing some sale events just because we cannot parse them. What we should do here is make sure that for every sale for which we cannot detect the price, we properly update the fillability status of the impacted orders. The logic would be something like:
```
if (cannotParseSale) {
  updateImpactedOrdersSetFillabilityStatusToFilled;
  addOrdersToOrderUpdatesByIdQueue;
}
```

Here's the sale parsing conditions I initially mentioned:
https://github.com/reservoirprotocol/indexer/blob/b05cfa714742d6826eb121be159b16c148e2fc94/src/sync/events/handlers/nftx.ts#L40-L52

2022-12-30 12:14 UTC, georgeroman commented on src/orderbook/orders/nftx/index.ts
> +
For now let's skip ERC20 pools (eg. pools for which the currency is not ETH).

2022-12-30 12:18 UTC, georgeroman commented
Let's include the orderId in the fill events. Also, for buy orders we should use fillEventsPartial while for sell orders we should use fillEventsOnChain. Had some issues recently with Sudoswap because of this.

https://github.com/reservoirprotocol/indexer/blob/b05cfa714742d6826eb121be159b16c148e2fc94/src/sync/events/handlers/nftx.ts#L99

https://github.com/reservoirprotocol/indexer/blob/b05cfa714742d6826eb121be159b16c148e2fc94/src/sync/events/handlers/nftx.ts#L209

See the sudoswap code and how we handle events, it should be exactly the same for NFTX:
https://github.com/reservoirprotocol/indexer/blob/b05cfa714742d6826eb121be159b16c148e2fc94/src/sync/events/handlers/sudoswap.ts#L18-L19

2022-12-30 12:24 UTC, georgeroman commented
Also, we should be careful about sweeping NFTX listings, since multiple tokens from the same poll would get dynamically priced. We want to have logic similar to Sudoswap:
https://github.com/reservoirprotocol/indexer/blob/b05cfa714742d6826eb121be159b16c148e2fc94/src/api/endpoints/execute/get-execute-buy/v6.ts#L208-L221

2022-12-30 12:25 UTC, georgeroman commented
Related to the above, we also want to return dynamic pricing information for NFTX listings (eg. the price points), similar to Sudoswap:
https://github.com/reservoirprotocol/indexer/blob/b05cfa714742d6826eb121be159b16c148e2fc94/src/api/endpoints/tokens/get-tokens/v5.ts#L801-L820

2023-01-04 02:29 UTC, lljxx1 commented on src/orderbook/orders/nftx/index.ts
> +
https://github.com/lljxx1/nft-exchanges/blob/main/nftx-protocol-v2/contracts/solidity/NFTXStakingZap.sol#L424

2023-01-04 02:30 UTC, lljxx1 commented on src/orderbook/orders/nftx/index.ts
> +
all pools are WETH

2023-01-05 12:03 UTC, closed without merging