feat: adding commits from res-1565
reservoirprotocol/indexer pull request #2921
Opened 2023-01-09 15:53 UTC by JadenDurnford

2023-01-09 15:55 UTC, JadenDurnford commented
https://linear.app/reservoir/issue/BE-72/communitycollectionsetid-api-filtering-parity

2023-01-09 16:42 UTC, nofir requested changes

2023-01-09 16:42 UTC, nofir commented on src/api/endpoints/orders/get-orders-bids/v5.ts
> +            "JOIN (SELECT DISTINCT contract FROM collections WHERE id IN ($/collectionsIds:csv/)) c ON orders.contract = c.contract";
this will filter by contract, rather then by collection

2023-01-10 19:48 UTC, nofir requested changes

2023-01-10 19:48 UTC, nofir commented on src/api/endpoints/orders/get-orders-asks/v4.ts
> +      .oxor("token", "contracts", "ids", "collectionsSetId")
Why did you add this? Just to make sure you are not breaking any existing beahvior.

2023-01-10 19:48 UTC, nofir commented on src/api/endpoints/orders/get-orders-asks/v4.ts
> +          collectionSetFilter = `JOIN (
I think you can simplify this (i also run an explain on the query and it seems much faster):

```SELECT
          orders.id,
          tokens.collection_id,
          orders.kind,
          orders.side,
          orders.token_set_id,
          orders.token_set_schema_hash,
          orders.contract,
          orders.maker,
          orders.taker,
          orders.currency,
          orders.price,
          orders.value,
          orders.currency_price,
          orders.currency_value,
          orders.normalized_value,
          orders.currency_normalized_value,
          orders.missing_royalties,
          dynamic,
          DATE_PART('epoch', LOWER(orders.valid_between)) AS valid_from,
          COALESCE(
            NULLIF(DATE_PART('epoch', UPPER(orders.valid_between)), 'Infinity'),
            0
          ) AS valid_until,
          orders.source_id_int,
          orders.quantity_filled,
          orders.quantity_remaining,
          orders.fee_bps,
          orders.fee_breakdown,
          COALESCE(
            NULLIF(DATE_PART('epoch', orders.expiration), 'Infinity'),
            0
          ) AS expiration,
          orders.is_reservoir,
          extract(epoch from orders.created_at) AS created_at,
          (
            CASE
              WHEN orders.fillability_status = 'filled' THEN 'filled'
              WHEN orders.fillability_status = 'cancelled' THEN 'cancelled'
              WHEN orders.fillability_status = 'expired' THEN 'expired'
              WHEN orders.fillability_status = 'no-balance' THEN 'inactive'
              WHEN orders.approval_status = 'no-approval' THEN 'inactive'
              ELSE 'active'
            END
          ) AS status,
          orders.updated_at
        FROM orders
        JOIN token_sets_tokens tst ON tst.token_set_id = orders.token_set_id
		JOIN tokens ON tokens.contract = tst.contract AND tokens.token_id = tokens.token_id
        WHERE orders.side = 'sell' AND tokens.collection_id IN ($/collectionsIds:csv/)```

2023-01-10 19:48 UTC, nofir commented on src/api/endpoints/orders/get-orders-bids/v5.ts
> +        if (query.collectionsSetId) {
Similar to the comment above. 
For bids, I would also test it with a collection set id with many collections (you sould be able to create it on goerli or ask angel for help) just to understand how much move heavy it is

2023-01-17 19:13 UTC, nofir approved these changes
LGTM. 

one comment is to format the **collectionSetFilter**  query in a more readable way in both apis:

```
          collectionSetFilter = `
            JOIN LATERAL (
              SELECT * FROM token_sets_tokens
              WHERE token_sets_tokens.token_set_id = orders.token_set_id LIMIT 1
            ) tst ON TRUE
            JOIN tokens ON tokens.contract = tst.contract AND tokens.token_id = tst.token_id
          `;
```

2023-01-30 20:34 UTC, merged