Flow
reservoirprotocol/indexer pull request #3155
Opened 2023-01-25 16:19 UTC by jfrazier-eth

2023-01-30 14:34 UTC, georgeroman requested changes

2023-01-30 14:34 UTC, georgeroman commented on package.json
> +    "@reservoir0x/sdk": "^0.0.302",
Let's keep a fixed version.

2023-01-30 14:34 UTC, georgeroman commented on src/api/endpoints/execute/get-execute-bid/v4.ts
> +                Sdk.Infinity.Addresses.Exchange[config.chainId]
This shouldn't get changed.

2023-01-30 14:55 UTC, jfrazier-eth commented on src/api/endpoints/execute/get-execute-bid/v4.ts
> +                Sdk.Infinity.Addresses.Exchange[config.chainId]
As in I should open another PR for this?

2023-01-31 15:27 UTC, georgeroman commented on src/api/endpoints/execute/get-execute-bid/v4.ts
> +                Sdk.Infinity.Addresses.Exchange[config.chainId]
My bad, I though this was some other part of the code.

2023-01-31 15:57 UTC, merged