feat: adding api details admin endpoint
reservoirprotocol/indexer pull request #3273
Opened 2023-02-07 18:09 UTC by JadenDurnford

2023-02-07 18:45 UTC, ipeleg commented on src/api/routes.ts
> +    path: "/api-keys/{key}/details",
Let's add admin prefix to the route

2023-02-07 18:45 UTC, ipeleg commented on src/api/endpoints/api-keys/get-api-key-details.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
Move this file to the admin endpoints folder

2023-02-08 07:14 UTC, nofir commented on src/api/routes.ts
> +    path: "/admin/{key}/details",
I think this should be `/admin/get-api-key` which follows the convention of other routes.

2023-02-09 14:13 UTC, nofir requested changes

2023-02-09 14:13 UTC, nofir commented on src/api/endpoints/admin/get-api-key-details.ts
> +      createdAt: Joi.string().allow(null),
can this actually be null?

2023-02-09 14:13 UTC, nofir commented on src/api/endpoints/admin/get-api-key-details.ts
> +        createdAt: apiKey?.createdAt.toString(),
new Date(apiKey.createdAt).toISOString()

2023-02-09 14:13 UTC, nofir commented on src/api/endpoints/admin/get-api-key-details.ts
> +        key: apiKey?.key,
its cleaner to return an error when the key isn't found rather than returning an empty object with 200 http status and using `apiKey?`

2023-02-09 22:14 UTC, JadenDurnford commented on src/api/endpoints/admin/get-api-key-details.ts
> +      createdAt: Joi.string().allow(null),
In theory it always defaults to the current time, but the column is still nullable so I added that just in case

2023-02-11 10:32 UTC, nofir commented on src/api/endpoints/admin/get-api-key-details.ts
> +      createdAt: Joi.string().allow(null),
Any reason the column is nullable?

2023-02-11 10:32 UTC, nofir approved these changes

2023-02-13 21:17 UTC, merged