feat: support seaport on-chain liquidlity
reservoirprotocol/indexer pull request #3404
Opened 2023-02-23 01:17 UTC by lljxx1

2023-02-23 14:36 UTC, georgeroman requested changes

2023-02-23 14:36 UTC, georgeroman commented on packages/indexer/src/orderbook/orders/seaport/index.ts
> +      // Check: order has a valid signature aand skip on-chain orders
Let's change this comment to `Check: order has a valid signature (or was validated on-chain)`

2023-02-23 14:36 UTC, georgeroman commented on packages/indexer/src/sync/events/handlers/seaport.ts
> +        const inoutData = exchange.contract.interface.decodeFunctionData("validate", tx.data);
Typo: should be `inputData`.

2023-02-23 14:36 UTC, georgeroman commented on packages/indexer/src/sync/events/handlers/seaport.ts
> +        const inoutData = exchange.contract.interface.decodeFunctionData("validate", tx.data);
Also, we should have different logic depending on the event kind (v1.1 or v1.4). If the version is v1.1 then we should get the order from the calldata. However, we should support internal calls as well so we should do it by parsing the call trace. If the version is v1.4 then we already have the order in the event and we should simply use that.

2023-02-23 14:36 UTC, georgeroman commented on packages/indexer/src/sync/events/handlers/seaport.ts
> +              kind: "single-token",
We shouldn't assume an order is `single-token`. Let's just remove the `kind` and make sure to wrap the order creation in a `try / catch` and ignore any errors.

2023-02-27 08:09 UTC, georgeroman requested changes

2023-02-27 08:09 UTC, georgeroman commented on packages/indexer/src/sync/events/data/seaport-v1.4.ts
> +  subKind: "seaport-v1.2-order-validated",
The sub-kind should be `seaport-v1.4-order-validated`.

2023-02-27 08:09 UTC, georgeroman commented on packages/indexer/src/sync/events/data/seaport-v1.4.ts
> +  addresses: { [SeaportV12.Addresses.Exchange[config.chainId]?.toLowerCase()]: true },
Does this compile? Should be `SeaportV14`.

2023-02-27 08:09 UTC, georgeroman commented on packages/indexer/src/sync/events/handlers/seaport.ts
> +            const order = new Sdk.Seaport.Order(config.chainId, {
We should differentiate between `seaport` and `seaport-v1.4` parameters. Maybe have separate arrays for each?

2023-02-27 08:09 UTC, georgeroman commented on packages/indexer/src/orderbook/orders/seaport-v1.4/index.ts
> +      if (!order.params.onChain) {
If we do it this way (by passing an `onChain` field in the order params) anyone could post orders with that field enabled and we will skip signature validation. What we should do instead is pass the `onChain` field in the `OrderInfo` object so that we as the backend have full control over when that's set or not. We should remove the `onChain` field from the SDK types.

2023-02-28 09:38 UTC, lljxx1 commented on packages/indexer/src/orderbook/orders/seaport-v1.4/index.ts
> +      if (!order.params.onChain) {
move to the metadata

2023-03-01 07:08 UTC, georgeroman commented on packages/indexer/src/sync/events/data/index.ts
>    seaportV14.orderFulfilled,
We also need to add `seaportV14.orderValidated` here.

2023-03-01 07:10 UTC, georgeroman commented on packages/indexer/src/sync/events/handlers/seaport.ts
> +              // onChainData.orders.push({
We should uncomment this.

2023-03-01 07:11 UTC, georgeroman commented on packages/indexer/src/sync/events/handlers/seaport.ts
> +            const inputData = exchange.contract.interface.decodeFunctionData(
Should we wrap this in a `try`/`catch`? Otherwise any failed call will stop the whole flow, which isn't what we want.

2023-03-01 07:43 UTC, georgeroman commented on packages/indexer/src/sync/events/handlers/seaport.ts
> +        // Hanlde seaport-v1.4
Typo: `Hanlde` instead of `Handle`. Same above for handling Seaport orders.

2023-03-01 07:53 UTC, georgeroman commented on packages/indexer/src/sync/events/handlers/seaport.ts
> +              onChain: true,
Let's remove this.

2023-03-01 07:54 UTC, georgeroman commented on packages/indexer/src/sync/events/handlers/seaport.ts
> +              onChain: true,
Let's remove this.

2023-03-01 11:08 UTC, merged