feat: support nftx with 0x
reservoirprotocol/indexer pull request #3448
Opened 2023-02-28 06:35 UTC by lljxx1

2023-03-28 12:51 UTC, georgeroman requested changes

2023-03-28 12:51 UTC, georgeroman commented on packages/contracts/test/router/v6/nftx/listings-zeroex.test.ts
> +  it("Fill listing", async () =>
Can we enable all tests?

2023-03-28 12:51 UTC, georgeroman commented on packages/contracts/test/router/v6/nftx/offers-zeroex.test.ts
> +  it("Accpect Offer", async () => testAcceptOffers(
Can we enable all tests?

2023-03-28 12:51 UTC, georgeroman commented on packages/indexer/yarn.lock
> -# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
I don't think we should remove this.

2023-03-28 12:51 UTC, georgeroman commented on packages/indexer/src/sync/events/handlers/nftx.ts
> +        const skipCheck = false;
I don't think we need this.

2023-03-28 12:51 UTC, georgeroman commented on packages/indexer/src/sync/events/handlers/nftx.ts
> +        const ftPool = await nftxUtils.getFtPoolDetails(baseEventParams.address, true);
This is not going to work because the ft pools are all uni-v2. What we should do instead is make an on-chain call to get `token0` and `token1` of the uni-v3 pool. Also we should have a caching layer (eg. `uniswap_v3_pools` - with a schema like `nftx_ft_pools`) so that we don't perform redundant on-chain calls.

2023-03-29 04:08 UTC, lljxx1 commented on packages/indexer/yarn.lock
> -# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
cause of the different versions of yarn I guess?

2023-04-21 02:45 UTC, lljxx1 commented on packages/indexer/src/sync/events/handlers/nftx.ts
> +        const ftPool = await nftxUtils.getFtPoolDetails(baseEventParams.address, true);
It works, uni-v3, and sushi pool both have `token0`, we could reuse the `nftx_ft_pools`.
At here we handle the uni-v3 Swap event and get the related NFTX vault. 
trigger an order to update

2023-04-21 02:45 UTC, lljxx1 commented on packages/indexer/src/sync/events/handlers/nftx.ts
> +        const skipCheck = false;
we need to cover the uni-v3 swap to re-fetch the price data

2023-04-24 08:56 UTC, georgeroman requested changes
One additional comment is that since now we support Uniswap V3 events we should also make sure to handle Uniswap V3 pools. At the moment, the `getFtPool` method only handles the old SushiSwap pool:
https://github.com/reservoirprotocol/indexer/blob/54bf81ec1857837036dc51d0f8e49b33375441f1/packages/indexer/src/utils/nftx/index.ts#L71-L94

2023-05-02 12:03 UTC, georgeroman requested changes

2023-05-02 12:03 UTC, georgeroman commented on packages/indexer/package.json
> +    "commander": "^10.0.0",
Why do we need this? Doesn't seem to be used.

2023-05-04 01:28 UTC, lljxx1 commented on packages/indexer/src/api/endpoints/execute/get-execute-buy/v6.ts
> +          // Attach the ZeroEx calldata
@georgeroman it's handled in `router.fillBidsTx`

2023-05-04 06:10 UTC, georgeroman commented on packages/indexer/src/api/endpoints/execute/get-execute-buy/v6.ts
> +          // Attach the ZeroEx calldata
Discussed and let's move this logic to the sdk for consistency.

2023-05-16 10:39 UTC, georgeroman commented
@lljxx1 I think we're missing the router code for filling the updated NFTX orders via `NFTXZeroExModule` instead of the old `NFTXModule`.

2023-05-16 11:19 UTC, georgeroman commented on packages/sdk/src/router/v6/router.ts
> +      nftxZeroModule: new Contract(
Let's rename this to `nftxZeroExModule`.

2023-05-17 09:45 UTC, merged