fix: add backfill to correct activities collectionId
reservoirprotocol/indexer pull request #3538
Opened 2023-03-08 00:14 UTC by tv3636

2023-03-10 17:49 UTC, ipeleg requested changes

2023-03-10 17:49 UTC, ipeleg commented on packages/indexer/src/jobs/backfill/backfill-activities-collection-id.ts
> +          activityId: cursor?.activityId,
Since the update will be done till no more rows, no need for the cursor

2023-03-10 20:34 UTC, tv3636 commented on packages/indexer/src/jobs/backfill/backfill-activities-collection-id.ts
> +          activityId: cursor?.activityId,
removed the cursor

2023-03-15 20:06 UTC, ipeleg approved these changes

2023-03-15 20:33 UTC, merged