Tv/platf 840 merge lastBuy and lastSell to includeLastSale with royaltyBreakdown
reservoirprotocol/indexer pull request #3555
Opened 2023-03-09 00:32 UTC by tv3636

2023-03-10 17:06 UTC, nofir requested changes

2023-03-10 18:54 UTC, tv3636 commented on packages/indexer/src/api/endpoints/tokens/get-user-tokens/v7.ts
> +                    r.last_buy_timestamp > r.last_sell_timestamp
updated to include the full lastSale, mirroring topBid

2023-03-13 20:13 UTC, nofir commented on packages/indexer/src/api/endpoints/tokens/get-user-tokens/v7.ts
> +            o.id AS last_sale_id,
Remind me, do we actually need the join with the orders table? don't you have all the info already in the sales table? Also, i see up until now lastBuy / lastSell only exposed value, timestamp, is the requirement to expose id, maker, source, etc?

2023-03-13 20:32 UTC, tv3636 commented on packages/indexer/src/api/endpoints/tokens/get-user-tokens/v7.ts
> +            o.id AS last_sale_id,
fill_events2 does not have `value` or `currency_value` which are both used to fill out the `JoiPrice` object (at least in other APIs), maker I included as I was going off of `topBid` as an example. 

initially the reason for joining orders and fill_events2 was to get the most complete royalty breakdown possible, since neither table has the complete data yet

2023-03-14 14:26 UTC, nofir reviewed
Looks good. One question, Why is there a large diff in v6?

2023-03-14 19:34 UTC, nofir approved these changes

2023-03-20 17:19 UTC, nofir approved these changes

2023-03-20 18:07 UTC, merged