feat: adding index for updated at ascending for asks endpoint
reservoirprotocol/indexer pull request #3696
Opened 2023-03-20 21:53 UTC by JadenDurnford

2023-03-21 20:07 UTC, ipeleg commented on packages/indexer/src/migrations/1643809164129_orders.sql
> +-- CREATE INDEX "orders_asks_updated_at_asc_id_index"
What is this for? and i guess if we want it we want to be uncommented right?

2023-03-22 18:49 UTC, JadenDurnford commented on packages/indexer/src/migrations/1643809164129_orders.sql
> +-- CREATE INDEX "orders_asks_updated_at_asc_id_index"
We created this index for the lightnode, @nofir should this be uncommented now that it has been successfully created?

2023-03-23 14:51 UTC, nofir submitted a review, later dismissed

2023-03-23 14:55 UTC, ipeleg requested changes

2023-03-23 14:55 UTC, ipeleg commented on packages/indexer/src/migrations/1643809164129_orders.sql
> +-- CREATE INDEX "orders_asks_updated_at_asc_id_index"
@JadenDurnford as it's now in a migration file that was already executed we can uncomment this

2023-03-24 20:27 UTC, nofir commented on packages/indexer/src/migrations/1643809164129_orders.sql
> +-- CREATE INDEX "orders_asks_updated_at_asc_id_index"
@JadenDurnford ust notice that we will have to run it manually in polygon, etc

2023-03-24 20:28 UTC, nofir approved these changes

2023-04-04 17:14 UTC, ipeleg approved these changes

2023-04-04 17:44 UTC, merged