feat: added option to filter sales endpoint by a list of tokens
reservoirprotocol/indexer pull request #3976
Opened 2023-04-05 15:41 UTC by arthurmr96

2023-04-07 13:48 UTC, nofir commented on packages/indexer/src/api/endpoints/transfers/get-sales/v4.ts
> +      tokens: Joi.array()
I would avoid having both token and tokens.
You can either:
- add a new v5 endpoint
- change the existing one to have "token" support both options. similar to here: https://github.com/reservoirprotocol/indexer/blob/578910fb5fd19ecd4685aef45f1a50e6b031c638/packages/indexer/src/api/endpoints/collections/get-collections/v5.ts#L57
-

2023-04-07 13:48 UTC, nofir commented on packages/indexer/src/api/endpoints/transfers/get-sales/v4.ts
> +    } else if (query.tokens) {
See comment above, you can merge both token and tokens logic

2023-04-07 13:48 UTC, nofir requested changes
left some comments

2023-04-07 22:59 UTC, arthurmr96 commented on packages/indexer/src/api/endpoints/transfers/get-sales/v4.ts
> +      tokens: Joi.array()
I added a new version then, so the property can be called `tokens` instead of `token`. It makes makes more sense to me the name be this one to support both options

2023-04-10 13:16 UTC, nofir approved these changes
LGTM. We will do some testing and merge.

2023-04-11 18:39 UTC, nofir requested changes

2023-04-11 20:44 UTC, arthurmr96 commented on packages/indexer/src/api/endpoints/transfers/get-sales/v4.ts
> +      tokens: Joi.array()
done!

2023-04-12 15:30 UTC, merged

2023-04-19 16:29 UTC, ipeleg commented
@arthurmr96 we're missing 
  server.route({
    method: "GET",
    path: "/sales/v5",
    options: transfersEndpoints.getSalesV5Options,
  });

in the routes.ts, can you add it?