Added alienswap contract and order type
reservoirprotocol/indexer pull request #3979
Opened 2023-04-05 16:26 UTC by xcaptain

This pull will close https://github.com/reservoirprotocol/indexer/pull/3946

I tried to not change exist code but adding new code, I have tested list, buy, cancel, bid, offer and bulk order on sepolia, all work, so I think it's ready to review.

@georgeroman please take a look

2023-04-06 01:43 UTC, xcaptain commented
Force pushed to resolve conflicts

tasks:
- [ ] deploy contract to all chains
- [ ] test offchain cancellation
- [ ] test erc1155 trading
- [ ] check some table to ensure data is correct

2023-04-06 06:27 UTC, xcaptain commented on packages/indexer/src/jobs/events-sync/write-buffers/nft-transfers.ts
> +      concurrency: 10,
I didn't change this line, introduce by other people's commits

2023-04-06 06:51 UTC, xcaptain commented on packages/sdk/src/alienswap/addresses.ts
> +export const OpenseaConduitKey: ChainIdToAddress = {
Should I use another name? Should I use the same conduitKey as seaport-v1.4?

2023-04-06 06:52 UTC, xcaptain commented on packages/sdk/src/alienswap/index.ts
> +// TODO: @Joey, use real addresses and abi
remove this line

2023-04-06 07:14 UTC, georgeroman commented on packages/indexer/src/api/endpoints/execute/get-execute-bid/v5.ts
> +      // put alienswap bulk orders together
Comment should be: `// Post any alienswap bulk orders together`

2023-04-06 07:21 UTC, georgeroman commented on packages/sdk/src/alienswap/addresses.ts
> +  [Network.Ethereum]: "0x7374FE94e34c209616cEc0610212DE13151D222f",
However, if the contract is not yet deployed let's just leave the object empty rather than putting here some mock addresses.

2023-04-06 07:29 UTC, georgeroman commented on packages/indexer/src/orderbook/orders/alienswap/index.ts
> +      const openSeaFeeRecipients = [
Let's replace this with the Alienswap fee recipients.

2023-04-06 07:30 UTC, georgeroman commented on packages/indexer/src/orderbook/orders/alienswap/index.ts
> +      let source: SourcesEntity | undefined = await sources.getOrInsert("opensea.io");
The source shouldn't be OS, but AlienSwap.

2023-04-06 08:26 UTC, xcaptain commented on packages/indexer/src/orderbook/orders/alienswap/index.ts
> +      if (metadata.fromOnChain || (isOpenSea && !order.params.signature)) {
for alienswap order save, `metadata.fromOnChain` will always be undefined, so I will remove the if part, only use else

2023-04-06 09:29 UTC, xcaptain commented on packages/sdk/src/alienswap/addresses.ts
> +export const OpenseaConduitKey: ChainIdToAddress = {
Fixed, changed to use `SeaportBase`

2023-04-06 09:29 UTC, xcaptain commented on packages/indexer/src/api/endpoints/execute/get-execute-bid/v5.ts
> +      // put alienswap bulk orders together
Fixed this comment

2023-04-06 09:30 UTC, xcaptain commented on packages/sdk/src/alienswap/addresses.ts
> +  [Network.Ethereum]: "0x7374FE94e34c209616cEc0610212DE13151D222f",
remove the addresses, will add real one in next PR

2023-04-06 09:31 UTC, xcaptain commented on packages/indexer/src/orderbook/orders/alienswap/index.ts
> +      // Make sure no zero signatures are allowed
removed this comment

2023-04-06 09:32 UTC, xcaptain commented on packages/indexer/src/orderbook/orders/alienswap/index.ts
> +      if (metadata.fromOnChain || (isOpenSea && !order.params.signature)) {
removed this if condition, because it will never be true

2023-04-06 09:33 UTC, xcaptain commented on packages/indexer/src/orderbook/orders/alienswap/index.ts
> +      const openSeaFeeRecipients = [
Removed this line, source will always read from db, also added `addPlatformAddress` and `supportedExchanges`

2023-04-06 09:47 UTC, xcaptain commented on packages/indexer/src/orderbook/orders/alienswap/index.ts
> +      let source: SourcesEntity | undefined = await sources.getOrInsert("opensea.io");
Changed, use `alienswap.xyz`

2023-04-06 09:47 UTC, xcaptain commented
@georgeroman please review again

2023-04-10 03:09 UTC, xcaptain commented
Rebased main to resolve conflicts, but now a new conflict `provider.ts` occurs, should be resolved after mergin main to development.

My next step is to deploy final contract to mainnet and goerli, so don't need to leave addresses empty

2023-04-11 12:46 UTC, xcaptain commented
I also submitted a draft to `seaport-oracle` to support alienswap contract, https://github.com/reservoirprotocol/seaport-oracle/pull/2
Can I reuse the oracle server or you want me to setup my own?

2023-04-12 14:00 UTC, georgeroman requested changes

2023-04-12 14:00 UTC, georgeroman commented on packages/indexer/src/sync/events/handlers/seaport.ts
> +              break;
I think the current logic is fine.

2023-04-12 15:30 UTC, xcaptain commented on packages/indexer/src/orderbook/orders/alienswap/build/utils.ts
> +  const conduitKey = Sdk.SeaportBase.Addresses.OpenseaConduitKey[config.chainId];
Thanks, changed to `ReservoirConduitKey` now

2023-04-12 15:30 UTC, xcaptain commented on packages/sdk/src/alienswap/addresses.ts
> +  [Network.Ethereum]: "",
removed the line

2023-04-12 15:30 UTC, xcaptain commented on packages/sdk/src/seaport-v1.4/order.ts
> +// export const EIP712_DOMAIN = (chainId: number, exchangeAddress: string) => ({
Removed these lines

2023-04-12 15:47 UTC, xcaptain commented
Merged main and pushed

2023-04-13 06:15 UTC, merged