feat: add cacheCollectionTopBidValue logic
reservoirprotocol/indexer pull request #4070
Opened 2023-04-12 05:32 UTC by d3or

2023-04-12 16:56 UTC, nofir requested changes

2023-04-12 16:56 UTC, nofir commented on packages/indexer/src/orderbook/orders/seaport-v1.4/index.ts
> +              await cacheCollectionTopBidValue(
I am not sure this is correct, the top bid on a single token is not necessarily the collection top bid. The caching should maybe be here: https://github.com/reservoirprotocol/indexer/blob/main/packages/indexer/src/jobs/collection-updates/top-bid-queue.ts

2023-04-13 13:05 UTC, nofir requested changes

2023-04-13 13:05 UTC, nofir commented on packages/indexer/src/jobs/collection-updates/top-bid-queue.ts
> +        const expiry = new Date();
I think you're missing a `if (collectionTopBid?.order_id)`, and then and `else` with removing the current collection top bid from the cache.

2023-04-13 13:05 UTC, nofir commented on packages/indexer/src/orderbook/orders/seaport-v1.4/index.ts
> +        const seaportBidPercentageThreshold = 50;
lets keep it 80 for the initial deployment and then make the change, i worry its going to overwhelm the system

2023-04-13 16:19 UTC, nofir requested changes

2023-04-13 16:19 UTC, nofir commented on packages/indexer/src/jobs/collection-updates/top-bid-queue.ts
> +          const [, , tokenId] = collectionTopBid.token_set_id.split(":");
i dont think the token set will have the token id in it, given that this logic only handles collection offers.

2023-04-13 16:19 UTC, nofir commented on packages/indexer/src/jobs/collection-updates/top-bid-queue.ts
> +              coalesce(
Are you sure its going to work? this is not included in the RETURNING clause (i am

2023-04-13 16:19 UTC, nofir commented on packages/indexer/src/jobs/collection-updates/top-bid-queue.ts
> +          const [, , tokenId] = collectionTopBid.token_set_id.split(":");
the collection id is actually passed to the job, why not just use that?

2023-04-13 18:25 UTC, nofir submitted a review, later dismissed

2023-04-19 18:12 UTC, ipeleg submitted a review, later dismissed

2023-04-20 17:05 UTC, ipeleg approved these changes

2023-04-20 18:59 UTC, merged