feat: add sell and buy order queue
reservoirprotocol/indexer pull request #4123
Opened 2023-04-14 15:03 UTC by d3or

2023-04-14 20:02 UTC, nofir requested changes

2023-04-14 20:02 UTC, nofir commented on packages/indexer/src/jobs/order-updates/buy-order-queue.ts
> +            trigger.kind === "new-order" &&
we need to change it to enable it for single token bid

2023-04-20 21:35 UTC, ipeleg approved these changes

2023-04-21 18:32 UTC, tv3636 commented on packages/indexer/src/jobs/order-updates/by-id-queue.ts
> -      const { id, trigger } = job.data as OrderInfo;
can you merge main/add this back in? it's not going to catch it as a merge conflict but the log i added for tracking order ingestion uses trigger in this job now

2023-04-25 14:20 UTC, ipeleg approved these changes

2023-04-25 14:38 UTC, merged