feat: add kafka consumer and event handler logic
reservoirprotocol/indexer pull request #4198
Opened 2023-04-19 18:23 UTC by d3or

2023-05-09 19:34 UTC, nofir requested changes

2023-05-09 19:34 UTC, nofir commented on packages/indexer/src/jobs/cdc/topics/indexer-order-events.ts
> +    await WebsocketEventRouter({
dont you need to disable the current logic to trigger the websocket (update by id, etc)

2023-05-09 19:34 UTC, nofir commented on packages/indexer/src/jobs/cdc/topics/indexer-ft-balances.ts
> +export class IndexerBalanceEventsHandler extends KafkaEventHandler {
shouldn't this be based on the nft_balances table?

2023-05-09 19:34 UTC, nofir commented on packages/indexer/src/jobs/cdc/topics/indexer-ft-approvals.ts
> +  topicName = "indexer.public.ft_approvals";
shouldnt this be based of the nft_approval_events? (it might mean the pr for approvals needs to change)

2023-05-09 19:34 UTC, nofir commented on packages/indexer/src/jobs/cdc/topics/indexer-ft-approvals.ts
> +  topicName = "indexer.public.ft_approvals";
I would assume so but we can confirm with Peter.

2023-05-09 19:34 UTC, nofir commented on packages/indexer/src/jobs/cdc/topics/indexer-bid-events.ts
> +  topicName = "indexer.public.bid_events";
I think you can remove this. top bid websocket wont be based on the cdc

2023-05-09 19:34 UTC, nofir commented on packages/indexer/src/jobs/cdc/index.ts
> +        if (handler.getTopics().includes(topic)) {
maybe add a log incase we actually consume a message that is not supported

2023-05-22 13:29 UTC, nofir requested changes

2023-05-22 13:29 UTC, nofir commented on packages/indexer/src/jobs/cdc/index.ts
> +const kafka = new Kafka({
Will that error out if client id is not configured? or it only matters when calling `.connect()`?

2023-05-22 13:29 UTC, nofir commented on packages/indexer/src/jobs/cdc/topics/KafkaEventHandler.ts
> +          this.handleDelete();
Do we actually listen to deletions from debeezium?

2023-05-22 13:29 UTC, nofir commented on packages/indexer/src/jobs/cdc/topics/KafkaEventHandler.ts
> +    const numericKeys = ["amount", "token_id"];
Is this maybe a setting on debeezium? Tracking `numericKeys` could end up being a pain if we expand this to more tables

2023-05-22 13:29 UTC, nofir commented on packages/indexer/src/jobs/cdc/topics/indexer-fill-events.ts
> +        log_index: payload.after.log_index,
Don't you also need to the batch index to uniquely identify the sale?

2023-05-22 13:29 UTC, nofir commented on packages/indexer/src/jobs/cdc/topics/indexer-fill-events.ts
> +        log_index: payload.after.log_index,
same as above

2023-05-22 13:29 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/approval-websocket-events-trigger-queue.ts
> +        const result = {
Any reason not to include the tx info? tx hash, log index, batch index? its standard wherever we include tx info

2023-05-22 13:29 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/bid-websocket-events-trigger-queue.ts
> +        console.log(error);
can be removed

2023-05-22 13:29 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/nft-balance-event-websocket-events-trigger-queue.ts
> +import { Job, Queue, QueueScheduler, Worker } from "bullmq";
did you mentioned that this is not needed?

2023-05-22 13:29 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/sale-websocket-events-trigger-queue.ts
> +              "\\\\" + data.tx_hash.replace("0x", "x")
you can pass the tx hash in the params and just do toBuffer. see here: https://github.com/reservoirprotocol/indexer/blob/f1c5234e423fbdb24af79ae7e70033c4016e43ac/packages/indexer/src/jobs/data-export/data-sources/sales.ts#L56

2023-05-22 13:40 UTC, d3or commented on packages/indexer/src/jobs/cdc/index.ts
> +const kafka = new Kafka({
it will not

2023-05-22 13:52 UTC, d3or commented on packages/indexer/src/jobs/cdc/topics/KafkaEventHandler.ts
> +          this.handleDelete();
yeah we are listening to deletions

2023-05-22 13:58 UTC, d3or commented on packages/indexer/src/jobs/websocket-events/nft-balance-event-websocket-events-trigger-queue.ts
> +import { Job, Queue, QueueScheduler, Worker } from "bullmq";
i talked to peter and we decided not to include it because it can be inferred from transfer event websocket

2023-05-22 14:06 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/nft-balance-event-websocket-events-trigger-queue.ts
> +import { Job, Queue, QueueScheduler, Worker } from "bullmq";
right, so isnt this file unnecessary?

2023-05-22 15:01 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/sale-websocket-events-trigger-queue.ts
> +            extract(epoch from fill_events_2.updated_at) updated_ts,
can be like created at

2023-05-22 15:01 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/sale-websocket-events-trigger-queue.ts
> +          updatedAt: new Date(r.updated_ts * 1000).toISOString(),
might be redundant as we dont use it for pagination

2023-05-22 16:38 UTC, nofir approved these changes

2023-05-22 16:58 UTC, merged