add contractsSetId filtering to /orders/asks/v4
reservoirprotocol/indexer pull request #4256
Opened 2023-04-25 10:29 UTC by mattetre

- Add `contractsSetId` filtering to the `/orders/asks/v4` endpoint

Influenced by the `contractsSetId` filtering seen here: https://github.com/reservoirprotocol/indexer/blob/main/packages/indexer/src/api/endpoints/activities/get-user-activity/v6.ts#L177-L182

2023-04-25 10:41 UTC, mattetre commented
Was also thinking it might make sense to add `contractsSetId` to the `oxor` query validation here: https://github.com/reservoirprotocol/indexer/pull/4256/files#diff-c77bff16f81bbd6e7506944b7c3cef0e4642dabed6c399150892bb1a7cac8df5R149 but I didn't see any other contract related fields in there so wanted to double check first

2023-04-25 22:31 UTC, ipeleg requested changes

2023-04-26 03:16 UTC, ipeleg commented on packages/indexer/src/api/endpoints/orders/get-orders-asks/v4.ts
Actually i'll just merge and add it

2023-04-26 03:16 UTC, ipeleg approved these changes

2023-04-26 03:17 UTC, merged