feat: add buy/sale websocket events
reservoirprotocol/indexer pull request #4366
Opened 2023-05-03 13:51 UTC by d3or

2023-05-03 23:37 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/buy-websocket-events-trigger-queue.ts
> +        if (data.trigger === "insert") eventType = "buy.created";
What is buy? Why dont just have a sale websocket? we have the side and the taker and the maker.

2023-05-09 18:36 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/sale-websocket-events-trigger-queue.ts
> +          isDeleted: Boolean(r.is_deleted),
Should we created a sale.deleted / sale.removed based on is_deleted? wdyt?

2023-05-10 13:33 UTC, d3or commented on packages/indexer/src/jobs/websocket-events/sale-websocket-events-trigger-queue.ts
> +          isDeleted: Boolean(r.is_deleted),
in what instances are is_deleted set to true?

2023-05-11 20:40 UTC, nofir approved these changes
approved but lets see if there is feedback regarding the payload

2023-05-11 20:40 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/sale-websocket-events-trigger-queue.ts
> +          isDeleted: Boolean(r.is_deleted),
after we mark it as deleted (usually when we detect an issue or when we revert sales due to orphan blocks)

2023-05-15 10:47 UTC, nofir requested changes

2023-05-15 10:47 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/sale-websocket-events-trigger-queue.ts
> +          isDeleted: Boolean(r.is_deleted),
you should remove this from the payload.

2023-05-22 16:58 UTC, merged