feat: add transfers websocket event
reservoirprotocol/indexer pull request #4385
Opened 2023-05-03 23:21 UTC by d3or

2023-05-08 21:27 UTC, nofir requested changes

2023-05-08 21:27 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/transfer-websocket-events-trigger-queue.ts
> +          address: eventData.address,
can you match the format of the api (txHash, token obj, etc) see here: 
https://github.com/reservoirprotocol/indexer/blob/05d59ec8029ddbb059d4a0e0b6a01c44bba6d697/packages/indexer/src/api/endpoints/transfers/get-transfers/v3.ts#L245

I see in the api we join with the fill events, need to confirm if that is needed as we will also have.

2023-05-09 19:11 UTC, nofir requested changes

2023-05-09 19:11 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/transfer-websocket-events-trigger-queue.ts
> +          tokenId: eventData.token_id,
see the format here:
https://github.com/reservoirprotocol/indexer/blob/2916a3f7a5536db9eba9ac75cab00498277a5e09/packages/indexer/src/api/endpoints/transfers/get-transfers/v3.ts#L244

i dont think we need the collection info

2023-05-11 02:06 UTC, d3or commented on packages/indexer/src/jobs/websocket-events/transfer-websocket-events-trigger-queue.ts
> +          tokenId: eventData.token_id,
do you think it might be beneficial to omit things like price / token name / token image? I feel as a large portion of the time these fields will be null because most NFTs dont have liquidity and images (most transfers are when they are minted initially)

2023-05-11 20:37 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/transfer-websocket-events-trigger-queue.ts
> +          tokenId: eventData.token_id,
I think it ok and we can add it if needed based on the current structure

2023-05-11 20:38 UTC, nofir approved these changes

2023-05-22 16:58 UTC, merged