Collectionswap integration
reservoirprotocol/indexer pull request #4413
Opened 2023-05-05 04:09 UTC by potato-cat69

2023-05-09 11:11 UTC, lljxx1 commented
looks good to me

2023-05-09 14:44 UTC, georgeroman requested changes

2023-05-09 14:44 UTC, georgeroman commented on packages/contracts/contracts/router/modules/exchanges/CollectionXyzModule.sol
> +      ICollectionRouter.PoolSwapSpecific[]
Would it be more gas-efficient to declare this outside of the `for` loop? Same applies below to `buyWithERC20`.

2023-05-09 14:44 UTC, georgeroman commented on packages/contracts/contracts/router/modules/exchanges/CollectionXyzModule.sol
> +      (, , uint256 price, ) = pools[i].getBuyNFTQuote(1);
Could this fail if there isn't enough liquidity in the pool? Might be worth putting this in the `try / catch` below.

2023-05-09 14:44 UTC, georgeroman commented on packages/indexer/src/migrations/1682410320474_collection-pools.sql
> +CREATE TABLE "collection_pools" (
Let's rename this to `collectionxyz_pools`.

2023-05-09 14:44 UTC, georgeroman commented on packages/indexer/src/models/sources/sources.json
> +  "7": {
This is not needed anymore, your source will automatically get inserted once a new order comes through.

2023-05-09 14:44 UTC, georgeroman commented on packages/sdk/src/collectionxyz/addresses.ts
> +export const CollectionPoolEnumerableETH: ChainIdToAddress = {
Addresses should all be lowercase.

2023-05-09 14:44 UTC, georgeroman commented on packages/sdk/src/router/v5/router.ts
> +    // The V5 router does not support filling CollectionXyz bids, so we fill directly
The v5 router is deprecated so this is not needed.

2023-05-09 14:44 UTC, georgeroman commented on packages/sdk/src/router/v6/router.ts
> +    if (details.some(({ kind }) => kind === "blur")) {
This was added by mistake?

2023-05-09 14:44 UTC, georgeroman commented on packages/sdk/src/router/v6/types.ts
> +      kind: "collection";
Let's rename this to "collectionxyz"

2023-05-09 14:44 UTC, georgeroman commented on packages/indexer/src/orderbook/orders/collectionxyz/index.ts
> +const getRoyaltyRecipient = async (
We already have this information, no need to make an on-chain call for every order:
https://github.com/reservoirprotocol/indexer/blob/bfc979efa63f3e5b5847de61d936158006b8858a/packages/indexer/src/orderbook/orders/looks-rare-v2/index.ts#L190-L198

2023-05-09 14:49 UTC, potato-cat69 commented on packages/contracts/contracts/router/modules/exchanges/CollectionXyzModule.sol
> +      (, , uint256 price, ) = pools[i].getBuyNFTQuote(1);
Nope, quote functions dont revert if the pool cant take it (this is intentional so users can know exactly how much they might need to top up to be able to buy more nfts with the pool)

2023-05-11 09:53 UTC, georgeroman requested changes

2023-05-11 09:53 UTC, georgeroman commented on packages/indexer/docker-compose.yaml
> +    command: postgres -N 2000
Just curious, had any issues running without `-N 2000`?

2023-05-11 09:53 UTC, georgeroman commented on packages/sdk/src/router/v6/router.ts
> +          const acceptedSet = detail.order.params.acceptedSet.map(BigInt);
As noted above, should pass the token ids via an additional field rather than assuming they are stored in the raw order data itself.

2023-05-11 09:53 UTC, georgeroman commented on packages/indexer/src/sync/events/handlers/collectionxyz.ts
> +        const txTrace = await utils.fetchTransactionTrace(txHash);
For both `swap-nft-out-pool` and `swap-nft-in-pool` I think we can use the event data rather than fetching the internal call trace. The reason we use tracing for sudoswap is because their events are badly designed and don't include any information:
https://github.com/reservoirprotocol/indexer/blob/92a7cca1be58b0f24578cb06a337aa9a4de0f7f1/packages/indexer/src/sync/events/data/sudoswap.ts#L7-L21

But in your case the events seem to include all data that we need. Tracing is also a bit more expensive, slower and more prone to weird issues, so would rather avoid it unless strictly necessary.

2023-05-12 01:50 UTC, potato-cat69 commented on packages/indexer/docker-compose.yaml
> +    command: postgres -N 2000
We would frequently get "Sorry too many connections"

2023-05-12 02:05 UTC, potato-cat69 commented on packages/sdk/src/collectionxyz/types.ts
> +  acceptedSet: string[];
ok, in that case ill also update the indexer to pass over bid orders for sets >100k. btw is it strictly or weakly greater than 100k? We saw some issues saving otherdeed orders on testnet which has 100k token ids exactly

2023-05-12 03:26 UTC, potato-cat69 commented on packages/indexer/src/sync/events/handlers/collectionxyz.ts
> +        // New pools will need encoded tokenIds from the AcceptsTokenIDs event
> // New pools will need encoded tokenIds from the AcceptsTokenIDs event

This step? unfortunately no, we dont store the token ids on chain, would be too expensive. its only emitted once via the creation/update events

2023-05-12 06:05 UTC, georgeroman requested changes

2023-05-12 06:05 UTC, georgeroman commented on packages/indexer/src/sync/events/data/collectionxyz.ts
> +      address indexed collectionxyz,
I assume the find and replace also updated `collection` to `collectionxyz` here, probably makes sense to keep as `collection` here and below.

2023-05-12 06:05 UTC, georgeroman commented on packages/indexer/src/sync/events/handlers/collectionxyz.ts
> +        const encodedTokenIds = hexToBytes(acceptsTokenIdsLog?.args["_data"] ?? "0x");
As mentioned above, let's pass this as hex and only convert in the `save` method.

2023-05-12 06:05 UTC, georgeroman commented on packages/indexer/src/sync/events/handlers/collectionxyz.ts
> +        const encodedTokenIds = hexToBytes(parsedLog.args["_data"] ?? "0x");
Same here

2023-05-12 06:14 UTC, georgeroman requested changes

2023-05-12 06:14 UTC, georgeroman commented on packages/indexer/src/orderbook/orders/collectionxyz/index.ts
> +const generateMerkleTree = (tokenIds: BigNumberish[]) => {
Any reason not to reuse the code we already have for the merkle roots: https://github.com/reservoirprotocol/indexer/blob/main/packages/sdk/src/common/helpers/merkle.ts?

2023-05-12 06:14 UTC, georgeroman commented on packages/indexer/src/orderbook/orders/collectionxyz/index.ts
> +  const [tradeBps, protocolBps, royaltyBps, carryBps] = (await poolContract.feeMultipliers()).map(
It's a bit redundant to make an on-chain call for every order. What about storing all the different fees in the `collectionxyx_pools` table in a `metadata JSONB` column. This way we would save these fees only the first time we encounter the pool (also when the fees get updated we'll have to refresh them). Is that viable?

2023-05-12 06:14 UTC, georgeroman commented on packages/indexer/src/orderbook/orders/collectionxyz/index.ts
> +  return poolContract.getRoyaltyRecipient(erc2981Recipient);
What's this additional call needed for? Maybe we can cache it somehow.

2023-05-12 07:43 UTC, potato-cat69 commented on packages/indexer/src/sync/events/data/collectionxyz.ts
> +      address indexed collectionxyz,
Yes, thanks for the catch

2023-05-12 07:55 UTC, potato-cat69 commented on packages/indexer/src/orderbook/orders/collectionxyz/index.ts
> +const generateMerkleTree = (tokenIds: BigNumberish[]) => {
importing that function causes a rather mysterious bug as shown in the ss below. Avoiding the import was as specific a fix as we could find

2023-05-12 07:57 UTC, potato-cat69 commented on packages/indexer/src/orderbook/orders/collectionxyz/index.ts
> +  const [tradeBps, protocolBps, royaltyBps, carryBps] = (await poolContract.feeMultipliers()).map(
Sure, I'll add a flag for fee updates to the orderinfo based on the event trigger

2023-05-13 07:43 UTC, georgeroman requested changes

2023-05-13 07:43 UTC, georgeroman commented on packages/indexer/src/orderbook/orders/collectionxyz/index.ts
> +const generateMerkleTree = (tokenIds: BigNumberish[]) => {
Hmm, was it a memory leak issue when starting the indexer? Make sure to import from `@reservoir0x/sdk` rather than `@reservoir/sdk/src`. Anyway, not a big deal.

2023-05-13 07:43 UTC, georgeroman commented on packages/indexer/src/orderbook/orders/collectionxyz/index.ts
> +      const externalFilterAddress = await poolContract.externalFilter();
Can we get this from the `collectionxyz_pools` table instead of making an on-chain call?

2023-05-13 08:29 UTC, potato-cat69 commented on packages/indexer/src/orderbook/orders/collectionxyz/index.ts
> +      const externalFilterAddress = await poolContract.externalFilter();
> Can we get this from the collectionxyz_pools table instead of making an on-chain call?

I don't think that would be the best approach because that table currently holds immutable params only; if we added externalFilter (a mutable param) to that table, we'd need to add separate logic for external filter updates. i'll put it in the raw_data column similar to the previous fixes

2023-05-13 08:30 UTC, potato-cat69 commented on packages/indexer/src/orderbook/orders/collectionxyz/index.ts
> +      const externalFilterAddress = await poolContract.externalFilter();
>Hmm, was it a memory leak issue when starting the indexer? Make sure to import from @reservoir0x/sdk rather than @reservoir/sdk/src. Anyway, not a big deal.

Not too sure, it oom's without logs so it's hard for us to trace with minimal architectural understanding. If you run the code locally with that fn imported it might be easier for you to see what's going on under the hood

2023-05-18 05:23 UTC, closed without merging