Update network.ts
reservoirprotocol/indexer pull request #4440
Opened 2023-05-06 22:00 UTC by westonnelson

Add $ARB and $NFTE on Arbitrum as currencies to be enabled for use on the marketplace.

2023-05-08 18:06 UTC, nofir requested changes

2023-05-08 18:06 UTC, nofir commented on packages/indexer/src/config/network.ts
> +            "0x912CE59144191C1204E64559FE8253a0e49E6548", // MUST BE LOWERCASE
can you make this lowercase?

2023-05-08 18:16 UTC, westonnelson commented on packages/indexer/src/config/network.ts
> +            "0x912CE59144191C1204E64559FE8253a0e49E6548", // MUST BE LOWERCASE
> can you make this lowercase?

Yes, done!

2023-05-08 20:47 UTC, nofir approved these changes

2023-05-08 20:48 UTC, nofir submitted a review, later dismissed

2023-05-08 20:52 UTC, nofir commented on packages/indexer/src/config/network.ts
> +            "0x912CE59144191C1204E64559FE8253a0e49E6548", // MUST BE LOWERCASE
@westonnelson the whitelisted currencies are only for currencies that are not supported by coingecko (which we use to keep currencies conversions up to date). I see both currencies are available on coingecko and already supported on our Arbitrum indexer.

2023-05-08 21:22 UTC, nofir commented on packages/indexer/src/config/network.ts
> +            "0x912CE59144191C1204E64559FE8253a0e49E6548", // MUST BE LOWERCASE
@westonnelson just to confirm, we can close this PR? 

You can see the currencies in coingecko here:
- https://www.coingecko.com/en/coins/arbitrum
- https://www.coingecko.com/en/coins/nftearth

2023-05-08 22:23 UTC, westonnelson commented on packages/indexer/src/config/network.ts
> +            "0x912CE59144191C1204E64559FE8253a0e49E6548", // MUST BE LOWERCASE
Hi there! - the challenge is that I see the currencies when we're using the Reservoir Indexer; but when we were using our own implementation of the Indexer and using Alchemy/GCP we could actually list the items in $ARB and $NFTE and now it is not functional.

There appears to be some sort of disconnect here; I do see seem as you mention but can't actually list when using Reservoir Indexer so thought this would be the solve. 

Wondering now what the root issue may be.

Screencaps attached for your review.
![Screenshot_20230508_171343_Brave.png](https://user-images.githubusercontent.com/29180454/236950758-d93f8cdc-9873-4518-8ed7-abc50baf251f.png)

![Screenshot_20230508_171359_Brave.png](https://user-images.githubusercontent.com/29180454/236950763-c99c546d-0f13-4233-a16b-049063991629.png)

![Screenshot_20230508_171411_Brave.png](https://user-images.githubusercontent.com/29180454/236950766-1fca6c31-d715-4d83-96cf-472ab258918f.png)

![Screenshot_20230508_171534_Brave.png](https://user-images.githubusercontent.com/29180454/236950769-7f7608bc-4487-401b-a0dd-a9df0e29c683.png)

2023-05-09 14:12 UTC, pedromcunha commented on packages/indexer/src/config/network.ts
> +            "0x912CE59144191C1204E64559FE8253a0e49E6548", // MUST BE LOWERCASE
Hi, this is likely an issue for ReservoirKit. Can you open up an issue in this repo so we can troubleshoot: https://github.com/reservoirprotocol/reservoir-kit

2023-05-11 20:42 UTC, nofir commented
Closing this for now

2023-05-11 20:42 UTC, closed without merging