fix: update sales latency metric
reservoirprotocol/indexer pull request #4457
Opened 2023-05-08 21:31 UTC by tv3636

2023-05-09 19:22 UTC, nofir requested changes

2023-05-09 19:22 UTC, nofir commented on packages/indexer/src/jobs/monitoring/latency-monitoring.ts
> +    const results = await idb.manyOrNone(
Also, might want to set a LIMIT, just in case (i saw its about 100 everytime so probably low risk)

2023-05-09 20:05 UTC, tv3636 commented on packages/indexer/src/jobs/monitoring/latency-monitoring.ts
> +    const results = await idb.manyOrNone(
added limit 1000 so we won't miss events but let me know if you think we should cap it lower. probably ok either way

2023-05-10 16:40 UTC, nofir approved these changes

2023-05-10 16:54 UTC, merged