feat: universal router
reservoirprotocol/indexer pull request #4481
Opened 2023-05-10 11:06 UTC by lljxx1

2023-05-11 16:35 UTC, georgeroman requested changes

2023-05-11 16:35 UTC, georgeroman commented on packages/contracts/contracts/router/modules/exchanges/UniversalSwapModule.sol
> +    PERMIT2 = IAllowanceTransfer(0x000000000022D473030F116dDEE9F6B43aC78BA3);
Let's make this configurable by passing via a constructor argument.

2023-05-11 16:35 UTC, georgeroman commented on packages/contracts/contracts/router/modules/exchanges/UniversalSwapModule.sol
> +    PERMIT2.approve(address(swap.params.tokenIn), address(UNIVERSAL_ROUTER), uint160(swap.params.amountInMaximum), uint48(block.timestamp + 100));
Any reason not to use `uint48(block.timestamp)` (without `+ 100`)? The permit should only hold for this transaction.

2023-05-11 16:35 UTC, georgeroman commented on packages/contracts/test/router/sdk.test.ts
> +    // expect(token3OwnerAfter).to.eq(buyer.address);
This fails?

2023-05-11 16:35 UTC, georgeroman commented on packages/sdk/src/router/v6/universal.ts
> +import { Interface, Result } from "@ethersproject/abi";
Can we rename this file to `universal-router`?

2023-05-11 16:35 UTC, georgeroman commented on packages/sdk/src/common/addresses.ts
> +export const UniversalRouter: ChainIdToAddress = {
Do we need this for anything?

2023-05-11 16:35 UTC, georgeroman commented on packages/sdk/src/router/v6/addresses.ts
> +  [Network.Ethereum]: "0x5cf0a457d2b6c003232184178e87c91248f73477",
Let's leave empty until deployed.

2023-05-11 16:35 UTC, georgeroman commented on packages/sdk/src/router/v6/universal.ts
> +        protocols: [Protocol.V3],
We should allow both V2 and V3. Also can remove the `maxSwapsPerPath` and `maxSplits` parameters.

2023-05-11 16:35 UTC, georgeroman commented on packages/sdk/src/router/v6/universal.ts
> +          // V3_SWAP_EXACT_OUT
We should also support `V2_SWAP_EXACT_OUT`.

2023-05-11 16:35 UTC, georgeroman commented on packages/contracts/contracts/router/modules/exchanges/UniversalSwapModule.sol
> +    Swap calldata swap,
We should support multiple `Swap` items (we want to allow the route to involve multiple swaps).

2023-05-11 16:35 UTC, georgeroman commented on packages/contracts/contracts/router/modules/exchanges/UniversalSwapModule.sol
> +    Swap calldata swap,
We should support multiple `Swap` items (we want to allow the route to involve multiple swaps).

2023-05-11 16:35 UTC, georgeroman commented on packages/sdk/src/router/v6/universal.ts
> +          // V3_SWAP_EXACT_OUT
This implies supporting multiple `swapParams`.

2023-05-12 00:55 UTC, lljxx1 commented on packages/contracts/test/router/sdk.test.ts
> +    // expect(token3OwnerAfter).to.eq(buyer.address);
It will fail before this PR

2023-05-12 00:57 UTC, lljxx1 commented on packages/sdk/src/common/addresses.ts
> +export const UniversalRouter: ChainIdToAddress = {
`UniversalSwapModule` needs that

2023-05-16 01:02 UTC, lljxx1 commented on packages/sdk/src/router/v6/universal.ts
> +        protocols: [Protocol.V3],
@georgeroman Once remove these, it will get an error:
`Failed to get 5 quotes`

2023-05-17 15:42 UTC, georgeroman requested changes

2023-05-17 15:42 UTC, georgeroman commented on packages/contracts/test/router/misc.test.ts
> +    universalSwapModule = await ethers
Can we use the new swap module in the tests? Just to make sure everything works we should replace the existing swap module with the universal one.

2023-05-17 15:42 UTC, georgeroman commented on packages/contracts/test/utils.ts
> +        '0x000000000022D473030F116dDEE9F6B43aC78BA3'
Can we use the SDK address here instead of hardcoding?

2023-06-13 15:17 UTC, georgeroman commented
After some more thought, looks like there's no benefit of using the universal router, we have an additional dependency in place while gaining nothing (the uniswap v3 router is now available on more chains compared to the universal router). So for now, going to close this.

2023-06-13 15:17 UTC, closed without merging