Tv/platf 1211 attribute issues with large collection
reservoirprotocol/indexer pull request #4582
Opened 2023-05-17 18:28 UTC by tv3636

2023-05-18 17:25 UTC, nofir commented on packages/indexer/src/api/endpoints/attributes/get-attributes-explore/v4.ts
> +          floorAskPrices: Joi.array().items(Joi.number().unsafe().allow(null)),
I think it might need to be a new version given that now we return null so we're basically changing the response or we can either return 0 which is like what the behavior now when there is no floor ask (might be a bit confusing).

wdyt?

2023-05-18 17:55 UTC, tv3636 commented on packages/indexer/src/api/endpoints/attributes/get-attributes-explore/v4.ts
> +          floorAskPrices: Joi.array().items(Joi.number().unsafe().allow(null)),
I think it's best to return null rather than 0 to avoid confusion. I'll move it to a new version to prevent breaking anyone who might be relying on numeric responses

2023-05-18 18:58 UTC, nofir requested changes

2023-05-18 18:58 UTC, nofir commented on packages/indexer/src/api/endpoints/attributes/get-attributes-explore/v5.ts
> +          floorAskPrices: Joi.array().items(Joi.number().unsafe().allow(null)),
aren't you missing the description?

2023-05-18 19:06 UTC, tv3636 commented on packages/indexer/src/api/endpoints/attributes/get-attributes-explore/v5.ts
> +          floorAskPrices: Joi.array().items(Joi.number().unsafe().allow(null)),
the description is updated on [line 22](https://github.com/reservoirprotocol/indexer/pull/4582/files#diff-e5a252d272c243b8fc4d21bbfb5221b63180999171e7c052e20a5fcce9f14c87R22) - not sure what you mean, can a description be added here?

2023-05-18 19:16 UTC, tv3636 commented on packages/indexer/src/api/endpoints/attributes/get-attributes-explore/v5.ts
> +            : [null],
updated to return an empty array

2023-05-18 20:50 UTC, nofir commented on packages/indexer/src/api/endpoints/attributes/get-attributes-explore/v5.ts
> +          floorAskPrices: Joi.array().items(Joi.number().unsafe().allow(null)),
I see. i thought maybe before it was on the property. any reason not to put it there?

2023-05-18 21:06 UTC, tv3636 commented on packages/indexer/src/api/endpoints/attributes/get-attributes-explore/v5.ts
> +          floorAskPrices: Joi.array().items(Joi.number().unsafe().allow(null)),
[On attributes/all it's in the main description](https://github.com/reservoirprotocol/indexer/blob/main/packages/indexer/src/api/endpoints/attributes/get-attributes-all/v4.ts#L19) like I have here. Do you mean putting it on `maxFloorAskPrices`? It seems confusing to put there since that's for setting a separate limit

2023-05-23 17:05 UTC, nofir approved these changes

2023-05-23 17:35 UTC, merged