feat: add extra image metadata to tokens table and tokens endpoints
reservoirprotocol/indexer pull request #4599
Opened 2023-05-18 14:42 UTC by ted-palmer

This pull request is dependent on [this PR](https://github.com/reservoirprotocol/metadata/pull/136) from the metadata api

2023-05-22 12:58 UTC, nofir commented on packages/indexer/src/utils/assets.ts
> +    return undefined;
I think undefined is returned by default.

2023-05-25 18:08 UTC, nofir requested changes

2023-05-25 18:08 UTC, nofir commented on packages/indexer/src/api/endpoints/tokens/get-tokens/v6.ts
> +            imageSmallUrl: Joi.string().allow("", null),
very small comment.. maybe just to keep consistent: imageSmall /imageLarge (unless peter asked specifically)

2023-05-25 18:08 UTC, nofir commented on packages/indexer/src/api/endpoints/tokens/get-tokens/v6.ts
> +            metadata: {
was the requirement to return the original in metadata?

maybe check if image_original_url exists and then decide if to return the metdata:

metadata: r.metadata.image_original_url ? { ... } : undefined

2023-05-25 18:08 UTC, nofir commented on packages/indexer/src/api/endpoints/tokens/get-tokens/v6.ts
> +            imageSmallUrl: Assets.getResizedImageUrl(r.image, 250),
maybe use ImageSize.small / ImageSize.large?

2023-05-25 18:08 UTC, nofir commented on packages/indexer/src/migrations/1643714286947_tokens.sql
> +  "metadata" JSONB,
this is wrong, you should create a new migration with metdata, otherwise this migration will never run

2023-05-25 19:12 UTC, ted-palmer commented on packages/indexer/src/api/endpoints/tokens/get-tokens/v6.ts
> +            metadata: {
Will do!

2023-05-25 19:15 UTC, ted-palmer commented on packages/indexer/src/api/endpoints/tokens/get-tokens/v6.ts
> +            imageSmallUrl: Assets.getResizedImageUrl(r.image, 250),
I think Peter wanted these as top level items because we intend to always return them. Is your suggestion pretty much to have an ImageSize object like so?:

```
ImageSize: {
        small: Assets.getResizedImageUrl(r.image, 250),
        large: Assets.getResizedImageUrl(r.image,1000),
}
```

2023-05-25 19:18 UTC, ted-palmer commented on packages/indexer/src/migrations/1643714286947_tokens.sql
> +  "metadata" JSONB,
Ah ok, didn't realize that's how it worked. How should I go about creating a new migration? I see the filenames have a some sort of unique number at the beginning

2023-05-25 20:57 UTC, nofir commented on packages/indexer/src/api/endpoints/tokens/get-tokens/v6.ts
> +            imageSmallUrl: Assets.getResizedImageUrl(r.image, 250),
No, its to use the enum you created so if we change the size, you dont need to change everywhere. (you might want to move it to the assets class
```
enum ImageSize {
  small = 250,
  medium = 512,
  large = 1000,
}
```

2023-05-25 20:58 UTC, nofir commented on packages/indexer/src/migrations/1643714286947_tokens.sql
> +  "metadata" JSONB,
create a new file with the current timestamp in milliseconds and then add the field.

see here: https://github.com/reservoirprotocol/indexer/blob/main/packages/indexer/src/migrations/1684443851969_collections-owners-count.sql

2023-05-30 14:33 UTC, nofir requested changes
looks good, left one comment

2023-05-30 15:20 UTC, ted-palmer commented on packages/indexer/src/migrations/1685050927714_tokens-metadata.sql
> +-- Down Migration
Yep! Done ✅

2023-05-30 22:56 UTC, nofir approved these changes

2023-06-08 18:55 UTC, merged