Tv/platf 1398 store opensea collection payment tokens
reservoirprotocol/indexer pull request #5044
Opened 2023-06-09 23:32 UTC by tv3636

2023-06-14 16:53 UTC, nofir requested changes

2023-06-14 16:53 UTC, nofir commented on packages/indexer/src/api/endpoints/collections/get-collection-supported-marketplaces/v2.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
Why is there a need for a v2 if we're only adding paymentTokens?

2023-06-14 16:53 UTC, nofir commented on packages/indexer/src/api/endpoints/collections/get-collection-supported-marketplaces/v2.ts
> +          paymentTokens: collectionResult.payment_tokens?.opensea,
Are you planning to do a backfill? alternatively you can do something similar to line 186 and try to get on the fly

2023-06-14 16:53 UTC, nofir commented on packages/indexer/src/jobs/token-updates/fetch-collection-metadata-job.ts
> +          paymentTokens: { opensea: collection.paymentTokens } ?? null,
I think you're missing logic to update in here:
https://github.com/reservoirprotocol/indexer/blob/6b3bd6d5c6339a1fcf6483152e832e4531db0481/packages/indexer/src/models/collections/index.ts#L134

2023-06-14 21:42 UTC, tv3636 commented on packages/indexer/src/jobs/token-updates/fetch-collection-metadata-job.ts
> +          paymentTokens: { opensea: collection.paymentTokens } ?? null,
not sure what you mean, something other than this? https://github.com/reservoirprotocol/indexer/pull/5044/files/1820d65df68cbf55c886e01a59cf8bcf952df8fc#diff-c98d5af98cf63c22904b691548fb3f095cdfd3afb1ee3573238e6b6472c076b1R78

2023-06-14 21:43 UTC, tv3636 commented on packages/indexer/src/api/endpoints/collections/get-collection-supported-marketplaces/v2.ts
> +          paymentTokens: collectionResult.payment_tokens?.opensea,
yes was thinking we would run a backfill

2023-06-19 14:05 UTC, nofir commented on packages/indexer/src/jobs/token-updates/fetch-collection-metadata-job.ts
> +          paymentTokens: { opensea: collection.paymentTokens } ?? null,
`    const query = `
      UPDATE collections SET
        metadata = $/metadata:json/,
        name = $/name/,
        slug = $/slug/,
        token_count = $/tokenCount/,
        updated_at = now()
      WHERE id = $/id/
      RETURNING (
                  SELECT
                  json_build_object(
                    'name', collections.name,
                    'metadata', collections.metadata
                  )
                  FROM collections
                  WHERE collections.id = $/id/
                ) AS old_metadata
    `;

    const values = {
      id: collection.id,
      metadata: collection.metadata || {},
      name: collection.name,
      slug: collection.slug,
      tokenCount,
    };`


this is the query that updates the collection, so your payment tokens wont be included in the update, no?

2023-06-19 15:45 UTC, tv3636 commented on packages/indexer/src/jobs/token-updates/fetch-collection-metadata-job.ts
> +          paymentTokens: { opensea: collection.paymentTokens } ?? null,
ah I see thanks, updated

2023-06-21 20:17 UTC, nofir approved these changes

2023-06-21 20:58 UTC, merged