WIP: Include caviar V1
reservoirprotocol/indexer pull request #5128
Opened 2023-06-14 16:42 UTC by outdoteth

2023-07-02 18:11 UTC, outdoteth commented on packages/sdk/src/router/v6/addresses.ts
> +  [Network.EthereumGoerli]: "todo insert here",
when should we deploy these? after the PR is merged or beforehand?

2023-07-02 18:12 UTC, outdoteth commented on packages/sdk/src/router/v6/router.ts
> +                { id: constants.HashZero, payload: [], timestamp: 0, signature: [] },
in caviar we verify that all NFTs that are sold into the pools are not marked as stolen by reservoir's oracle.
should the stolen NFT attestation from the oracle be fetched on the server here, or should it be passed from the client?

2023-07-03 10:43 UTC, georgeroman requested changes

2023-07-03 10:43 UTC, georgeroman commented on packages/indexer/src/common/logger.ts
> +    level: "info",
Unrelated change, let's leave this as it was

2023-07-03 10:43 UTC, georgeroman commented on packages/indexer/src/sync/events/handlers/utils/index.ts
> +  // TODO: remove this, only here for testing
Leftover?

2023-07-03 10:43 UTC, georgeroman commented on packages/sdk/src/caviar-v1/addresses.ts
> +  [Network.Ethereum]: "0xa964D6E8d90E5Cd12592a8EF2b1735daE9Ba0840",
Addresses should be lowercase

2023-07-03 10:43 UTC, georgeroman commented on packages/sdk/src/caviar-v1/order.ts
> +    tokenId: order.tokenId,
For safety, let's stringify this: `order.tokenId ? s(order.tokenId) : order.tokenId`

2023-07-03 10:43 UTC, georgeroman commented on packages/sdk/src/router/v6/addresses.ts
> +  [Network.EthereumGoerli]: "todo insert here",
Before, I'll take care of deploying before merging

2023-07-03 10:43 UTC, georgeroman commented on packages/sdk/src/router/v6/router.ts
> +                { id: constants.HashZero, payload: [], timestamp: 0, signature: [] },
I think it should be fetched from the server. See how it's done below, in the `collectionxyz` case (we use the `extraArgs` field).

2023-07-03 10:43 UTC, georgeroman commented on packages/sdk/src/router/v6/router.ts
> +import { constants } from "ethers";
We already import `HashZero`

2023-07-03 14:35 UTC, outdoteth commented on packages/sdk/src/caviar-v1/exchange.ts
> +      headers: { "x-api-key": process.env.ORACLE_API_KEY as string },
is this the correct way to pass in the env var?

2023-07-03 14:36 UTC, outdoteth commented on packages/sdk/src/router/v6/router.ts
> +                { id: constants.HashZero, payload: [], timestamp: 0, signature: [] },
added an Exchange class that has a method to fetch the stolen proof.

2023-07-03 14:45 UTC, georgeroman commented on packages/sdk/src/caviar-v1/exchange.ts
> +      headers: { "x-api-key": process.env.ORACLE_API_KEY as string },
We should probably use `inject` instead: https://github.com/reservoirprotocol/indexer/blob/ae578a3613044a6e14e537b28b8d3ceb15386a04/packages/indexer/src/api/endpoints/management/post-simulate-order/v1.ts#L169-L182

Also, we should pass the signature to the SDK via the `extraArgs` field, as below: https://github.com/reservoirprotocol/indexer/blob/ae578a3613044a6e14e537b28b8d3ceb15386a04/packages/indexer/src/orderbook/orders/index.ts#L482-L499

2023-07-03 16:38 UTC, outdoteth commented on packages/indexer/src/orderbook/orders/index.ts
> +      });
@georgeroman like this?

2023-07-03 16:39 UTC, outdoteth commented on packages/sdk/src/caviar-v1/exchange.ts
> +      headers: { "x-api-key": process.env.ORACLE_API_KEY as string },
cool, moved it around. got rid of the exchange and switched to inject and extraArgs

2023-07-14 06:10 UTC, merged