feat: add cryptopunks module for aggregator 'router'
reservoirprotocol/indexer pull request #5143
Opened 2023-06-15 08:47 UTC by DessertHeart

add cryptopunks module contract and its setup ts codes in router.ts

2023-06-16 07:54 UTC, georgeroman requested changes

2023-06-16 07:54 UTC, georgeroman commented on packages/contracts/contracts/router/modules/exchanges/CryptoPunksModule.sol
> +            PUNK_MARKETPLACE.transferPunk(
This will succeed in all cases, so we can simply move it inside the `{}` of the `try / catch` above.

2023-06-16 07:54 UTC, georgeroman commented on packages/contracts/contracts/router/modules/exchanges/CryptoPunksModule.sol
> +        OfferParams calldata params
For simplicity and consistency with the rest of the modules, let's have this method fill a single offer rather than multiple ones.

2023-06-16 07:54 UTC, georgeroman commented on packages/contracts/contracts/router/modules/exchanges/CryptoPunksModule.sol
> +        OfferParams calldata params
Also, we should integrate fees:https://github.com/reservoirprotocol/indexer/blob/8cea061ab2dc27eb802e89e7b5da82cc83e04646/packages/contracts/contracts/router/modules/exchanges/LooksRareV2Module.sol#L114

2023-06-16 07:54 UTC, georgeroman commented on packages/contracts/contracts/router/modules/exchanges/CryptoPunksModule.sol
> +        require(
No need to have any assertions, the router will make sure the calldata is properly built

2023-06-16 07:54 UTC, georgeroman commented on packages/contracts/contracts/router/modules/exchanges/CryptoPunksModule.sol
> +            PUNK_MARKETPLACE.withdraw()
Let's move this inside the `try / catch` `{}` from above

2023-06-16 07:54 UTC, georgeroman commented on packages/contracts/contracts/router/modules/exchanges/CryptoPunksModule.sol
> +        (bool success,) = payable(seller).call{value: sellOrder.price}("");
Let's use `_sendAllETH`:https://github.com/reservoirprotocol/indexer/blob/8cea061ab2dc27eb802e89e7b5da82cc83e04646/packages/contracts/contracts/router/modules/exchanges/BaseExchangeModule.sol#L156-L158

2023-06-16 07:54 UTC, georgeroman commented on packages/sdk/src/router/v6/router.ts
> +    const cryptoPunkDetails: ListingDetails[] = [];
Now that we fill via the router, we can remove the direct filling logic:
![image](https://github.com/reservoirprotocol/indexer/assets/30772943/85d855a4-cc9c-4460-8836-5495312e7ba1)

2023-06-16 07:54 UTC, georgeroman commented on packages/sdk/src/router/v6/router.ts
> +        //  Attention:
I think splitting the approval and the sell transactions is risky since someone could front-run the sell transaction and send the punk to themselves instead of having it sold. For this reason, it probably make sense to disallow filling offers via the router, and always fill directly.

2023-06-19 02:48 UTC, DessertHeart commented on packages/contracts/contracts/router/modules/exchanges/CryptoPunksModule.sol
> +        OfferParams calldata params
I see, but I found that we also implemented multiple 'sell' in some modules like 'NFTXModule'. So in this case, we still should use 'single fill' instead?

2023-06-19 03:42 UTC, DessertHeart commented on packages/sdk/src/router/v6/router.ts
> +        //  Attention:
totally agreed. So how about I just remove the logic for filling offers in router.ts?

2023-06-19 05:49 UTC, DessertHeart commented on packages/contracts/contracts/router/modules/exchanges/CryptoPunksModule.sol
> +        OfferParams calldata params
btw, for 'chrageFee' method in contract, is it a interface allowing aggregator(like us) charge extra tx fees? if it is, have u guys packed the method into APIs? if not, how could we do to make it?

2023-06-20 08:57 UTC, georgeroman commented on packages/sdk/src/router/v6/router.ts
> +        //  Attention:
Yep, let's do that

2023-06-20 08:57 UTC, georgeroman commented on packages/contracts/contracts/router/modules/exchanges/CryptoPunksModule.sol
> +        OfferParams calldata params
If we remove the logic for filling offers via the router (due to the risks involved), this isn't needed anymore

2023-06-20 08:59 UTC, georgeroman requested changes

2023-06-20 08:59 UTC, georgeroman commented on packages/contracts/contracts/router/modules/exchanges/CryptoPunksModule.sol
> +    // --- Multiple sell Punks ---
As discussed, `batchSellPunks` and `_sell` aren't needed anymore.

2023-06-21 09:35 UTC, merged