feat: support payment processor
reservoirprotocol/indexer pull request #5211
Opened 2023-06-20 03:10 UTC by lljxx1

2023-06-20 08:49 UTC, georgeroman requested changes

2023-06-20 08:49 UTC, georgeroman commented on packages/sdk/src/payment-processor/types.ts
> +  sellerMasterNonce: BigNumberish;
Do we actually need these two? They don't seem to be present in the contract `MatchedOrder` struct.

2023-06-20 08:49 UTC, georgeroman commented on packages/sdk/src/payment-processor/types.ts
> +  listingSignature?: string;
Let's store the `v`, `r` and `s` directly instead of the compact signature, to match the contract code.

2023-06-20 08:49 UTC, georgeroman commented on packages/sdk/src/payment-processor/types.ts
> +export type MatchOrder = {
Let's rename this to `MatchedOrder`, to match the contract code.

2023-06-20 08:49 UTC, georgeroman commented on packages/sdk/src/payment-processor/order.ts
> +  public params: Types.MatchOrder;
I think `MatchedOrder` should only be used when filling, otherwise we should store either `SaleApproval` or `OfferApproval` directly (since these are the actual order formats).

2023-06-20 08:49 UTC, georgeroman commented on packages/sdk/src/payment-processor/types.ts
> +export type SaleApproval = {
We should store the signatures in the `SaleApproval` and `OfferApproval` structs.

2023-06-20 08:49 UTC, georgeroman commented on packages/sdk/src/payment-processor/order.ts
> +  public async signOffer(signer: TypedDataSigner) {
We should have a single method for signing that detects the kind automatically (`sale-approval` vs `offer-approval` vs `collection-offer-approval`).

2023-06-26 10:27 UTC, georgeroman requested changes

2023-06-26 10:27 UTC, georgeroman commented on packages/indexer/src/sync/events/data/payment-processor.ts
> +  topic: "0x7ed668b30822ae5c7db7b4a32f84e6645250bb6db0d1fc73eeb484c5b34b1d1b",
The first 3 events have the same topic, that seems wrong.

2023-06-26 10:27 UTC, georgeroman commented on packages/indexer/src/sync/events/handlers/payment-processor.ts
> +        const newNonce = parsedLog.args["none"].toString();
Typo, should be `nonce` instead of `none`

2023-06-26 10:27 UTC, georgeroman commented on packages/sdk/src/payment-processor/addresses.ts
> +  [Network.Ethereum]: "0x009a1dc629242961c9e4f089b437afd394474cc0",
Let's also add the Goerli address in here, we'll be testing there.

2023-06-26 10:27 UTC, georgeroman commented on packages/sdk/src/payment-processor/types.ts
> +  sellerMasterNonce: string;
Is this and buyerMasterNonce needed for anything?

2023-06-26 10:27 UTC, georgeroman commented on packages/sdk/src/payment-processor/exchange.ts
> +  public async getNonce(provider: Provider, user: string): Promise<BigNumber> {
Let's rename this to `getMasterNonce`

2023-06-26 10:27 UTC, georgeroman commented on packages/indexer/src/sync/events/handlers/payment-processor.ts
> +        // const parsedLog = eventData.abi.parseLog(log);
Why do we need to use call tracing instead of the emitted events?

2023-06-26 10:27 UTC, georgeroman commented on packages/indexer/src/orderbook/orders/payment-processor/index.ts
> +      let conduit = Sdk.LooksRareV2.Addresses.Exchange[config.chainId];
This is wrong

2023-06-26 10:27 UTC, georgeroman commented on packages/indexer/src/orderbook/orders/payment-processor/index.ts
> +      // // Check: order is valid
We should probably enable this check

2023-06-26 10:27 UTC, georgeroman commented on packages/indexer/src/orderbook/orders/payment-processor/index.ts
> +
Initially we only want to support orders on contracts with the default security policy id. So we should add a check for that as well (on-chain call is fine).

2023-06-26 12:12 UTC, lljxx1 commented on packages/sdk/src/payment-processor/types.ts
> +  sellerMasterNonce: string;
yeah, when validating the signature, both are needed

2023-06-26 12:14 UTC, lljxx1 commented on packages/indexer/src/sync/events/handlers/payment-processor.ts
> +        // const parsedLog = eventData.abi.parseLog(log);
need to compute the order ID via Matched Order

2023-06-28 12:30 UTC, merged