Integrate Midaswap
reservoirprotocol/indexer pull request #5540
Opened 2023-07-12 10:56 UTC by LXVC

2023-07-19 10:06 UTC, LXVC commented on packages/indexer/src/sync/events/data/midaswap.ts
> +  numTopics: 4,
correct!

2023-07-19 10:17 UTC, LXVC commented on packages/indexer/src/orderbook/orders/midaswap/index.ts
> +                ids,
Will this automatically set the 'fillability_status' field of these orders to 'cancelled'?

2023-07-19 10:20 UTC, LXVC commented on packages/indexer/src/orderbook/orders/index.ts
> +
Other exchanges also have two of the same logic in this file

2023-07-19 12:26 UTC, lljxx1 commented on packages/indexer/src/orderbook/orders/midaswap/index.ts
> +                ids,
yeah. link them by the `ordeId`

2023-07-21 09:36 UTC, lljxx1 commented on packages/indexer/src/orderbook/orders/midaswap/index.ts
> +                ids,
let's only delete the orders that are not `filled`.

2023-07-21 09:36 UTC, lljxx1 commented on packages/indexer/src/orderbook/orders/midaswap/index.ts
> +          await idb.none(`DELETE FROM orders WHERE orders.id = $/id/`, { id });
If the order may be `filled`, please avoid deleting the order directly

2023-07-21 09:36 UTC, lljxx1 commented on packages/indexer/src/orderbook/orders/midaswap/index.ts
> +
same as above

2023-07-21 09:36 UTC, lljxx1 commented on packages/indexer/src/orderbook/orders/midaswap/index.ts
> +              const source = await sources.getOrInsert("midaswap");
same as above

2023-07-21 10:03 UTC, LXVC commented on packages/indexer/src/orderbook/orders/midaswap/index.ts
> +          await idb.none(`DELETE FROM orders WHERE orders.id = $/id/`, { id });
One question, if an order fires the 'filled' event in handler, will the change happen before or after the 'save' function is executed? Or not sure?

2023-07-21 10:14 UTC, LXVC commented on packages/indexer/src/orderbook/orders/midaswap/index.ts
> +              const id = getBuyOrderId(pool.address, lpTokenId, randomUUID());
There is a solution, but it will cause some problems. The parameter for `getBuyOrderId` will become `(pool: string, lpTokenId: string, bin: string, index: number)`. This is not a problem when creating a `buy` order, but when the order is traded, there is no `index`. Therefore, when trading, I have to search for the `index` from 0 until I find a "fillable" order. Is this acceptable?

2023-07-23 08:59 UTC, georgeroman requested changes

2023-07-23 08:59 UTC, georgeroman commented on packages/indexer/src/sync/events/handlers/index.ts
> +  ) => Promise<void> | Promise<OnChainData | undefined>
Why this change? Seems unrelated to the integration.

2023-07-23 08:59 UTC, georgeroman commented on packages/sdk/src/midaswap/order.ts
> +  public static getSellPrice = (bin: number, freeRate = 0, roralty = 0) => {
Should be `royalty`, below as well.

2023-07-23 08:59 UTC, georgeroman commented on packages/contracts/package.json
> +    "decimal.js": "^10.4.3",
Where is this used? If possible, let's not add any new dependencies.

2023-07-23 08:59 UTC, georgeroman commented on packages/indexer/src/common/joi.ts
> +  } else if (kind === "midaswap") {
Can we just add a new `pool` field in the raw data which includes the LP id? Would try to avoid adding another branch.

2023-07-23 08:59 UTC, georgeroman commented on packages/indexer/src/orderbook/orders/utils.ts
> +  eventName?: string;
These fields shouldn't be here, this is a generic type that covers all orders so we should avoid adding anything specific to a particular exchange.

2023-07-23 08:59 UTC, georgeroman commented on packages/indexer/src/orderbook/orders/utils.ts
> +  eventName?: string;
If needed, should include these fields in the `orderParams`.

2023-07-23 08:59 UTC, georgeroman commented on packages/sdk/src/midaswap/order.ts
> +import Decimal from "decimal.js";
As mentioned in one comment above, let's try to avoid adding a new dependency.

2023-07-24 05:17 UTC, georgeroman commented on packages/indexer/src/orderbook/orders/midaswap/index.ts
> +              const id = getBuyOrderId(pool.address, lpTokenId, randomUUID());
Could we use call tracing to get the index from any sub-calls? See how we handle sudoswap-v2 sales.

2023-07-24 05:17 UTC, georgeroman commented on packages/indexer/src/orderbook/orders/midaswap/index.ts
> +          await idb.none(`DELETE FROM orders WHERE orders.id = $/id/`, { id });
The save will happen after.

2023-07-24 05:46 UTC, LXVC commented on packages/sdk/src/midaswap/order.ts
> +  public static getSellPrice = (bin: number, freeRate = 0, roralty = 0) => {
Sorry, I don't understand. Should I rename `getSellPrice`?

2023-07-24 05:55 UTC, LXVC commented on packages/indexer/src/common/joi.ts
> +  } else if (kind === "midaswap") {
So the `pool` field will not be an address, will be `${pair}_${lpTokenId}`, is that OK?

2023-07-24 06:21 UTC, LXVC commented on packages/indexer/src/orderbook/orders/midaswap/index.ts
> +              const id = getBuyOrderId(pool.address, lpTokenId, randomUUID());
No can do. Our contract does not store index information, the NFTs under the same lpTokenId are unordered from the contract's perspective, index is an off-chain concept.

2023-07-24 06:21 UTC, LXVC commented on packages/sdk/src/midaswap/order.ts
> +import Decimal from "decimal.js";
I'll try.

2023-07-24 08:15 UTC, georgeroman commented on packages/indexer/src/common/joi.ts
> +  } else if (kind === "midaswap") {
Yes, just make sure to keep the `pair` field, which is gong to be an address.

2023-08-10 15:11 UTC, georgeroman commented
Closing this, already merged in a different PR

2023-08-10 15:11 UTC, closed without merging