Tv/platf 1673 support token attribute ws
reservoirprotocol/indexer pull request #5563
Opened 2023-07-12 23:07 UTC by tv3636

2023-07-13 20:00 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/attribute-websocket-events-trigger-queue.ts
> +            JOIN attributes
is there any impact as query performance if joining with attributes? we might be able to live without it

2023-07-14 16:22 UTC, nofir requested changes

2023-07-14 16:22 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/token-attribute-websocket-events-trigger-queue.ts
> +  contract: "token_attributes.contract",
we decided to check if updated is even a scenario

2023-07-14 16:22 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/token-attribute-websocket-events-trigger-queue.ts
> +const QUEUE_NAME = "token-attribute-websocket-events-trigger-queue";
needs to change to a rabbitmq job

2023-07-17 19:35 UTC, nofir requested changes

2023-07-17 19:35 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/token-attribute-websocket-events-trigger-queue.ts
> +import { logger } from "@/common/logger";
can change the name to -job instead of -queue? that has been the approach so far.

2023-07-17 19:35 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/token-attribute-websocket-events-trigger-queue.ts
> +  updated_at: "updatedAt",
i dont think "updated_at" should be in the changed mapping. if the only thing that change is the updated_at, then we should not send an event

2023-07-17 19:35 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/token-attribute-websocket-events-trigger-queue.ts
> +            logger.info(this.queueName, "update token attributes");
please add the before / after so we can understand better what are the usecases

2023-07-19 17:53 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/token-attribute-websocket-events-trigger-job.ts
> +      const baseQuery = `
i realized that this needs to be changed to use the data from the data.after as we have all the data alredy (similar to the stories to switch to using cdc data)

2023-07-19 17:55 UTC, tv3636 commented on packages/indexer/src/jobs/websocket-events/token-attribute-websocket-events-trigger-job.ts
> +      const baseQuery = `
isn't it already? line 47 and 48

2023-07-19 18:27 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/token-attribute-websocket-events-trigger-job.ts
> +      const baseQuery = `
i meant that there is no need to make a query to the db which you are doing in lines 29 - 45

2023-07-20 13:30 UTC, nofir requested changes

2023-07-20 13:30 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/token-attribute-websocket-events-trigger-job.ts
> +        data: data.after,
i see you changed to use the data from the event but you should still keep the same response standard:
`{    
            token: {
                  contract: fromBuffer(r.contract),
                  tokenId: r.token_id,
                },
                collection: {
                  id: r.collection_id,
                },
                key: r.key,
                value: r.value,
                createdAt: r.created_at,
                updatedAt: r.updated_at,
              }`

2023-07-20 20:28 UTC, nofir approved these changes

2023-07-21 17:40 UTC, nofir approved these changes

2023-07-21 18:28 UTC, merged