feat: add volume and pricing to recent sales
reservoirprotocol/indexer pull request #5586
Opened 2023-07-13 21:46 UTC by lunarmayor

2023-07-14 16:21 UTC, nofir requested changes

2023-07-14 16:21 UTC, nofir commented on packages/indexer/src/elasticsearch/indexes/activities/index.ts
> +                        type: ["sale", "mint"],
I see you are also querying mints, i did not backfill the pricingDecimal for mints which i guess makes sense for paid mints. so i might need to do that before you make the change.

also, to filter out free mints, you might want to add a filter to only include price > 0

2023-07-14 18:26 UTC, lunarmayor commented on packages/indexer/src/elasticsearch/indexes/activities/index.ts
> +                        type: ["sale", "mint"],
I'm also aggregating the count so still need to include the free mints

2023-07-17 19:41 UTC, nofir approved these changes

2023-07-18 15:11 UTC, merged