feat: enabled changed on transfers in progress
reservoirprotocol/indexer pull request #5611
Opened 2023-07-17 16:06 UTC by tv3636

2023-07-17 16:20 UTC, nofir requested changes

2023-07-17 16:20 UTC, nofir commented on packages/indexer/src/jobs/index.ts
> -import * as transferWebsocketEventsTriggerQueue from "@/jobs/websocket-events/transfer-websocket-events-trigger-queue";
I would make another pr to remove the queue, otherwise, you would lose visibility to when the queue is empty of any pending messages.

2023-07-17 16:20 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/transfer-websocket-events-trigger-queue.ts
> -import { Job, Queue, QueueScheduler, Worker } from "bullmq";
to continue the comment from before, you should have created a new file with the rabbitmq job. im sorry if i wasnt clear, it mainly to not lose any messages in the queue

2023-07-17 16:20 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/transfer-websocket-events-trigger-queue.ts
> +      if (data.after.is_deleted) eventType = "transfer.deleted";
it might make sense to check if data.before.is_deleted === 0 also so we wont trigger a deleted more than once. @d3or wdyt?

2023-07-17 16:20 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/transfer-websocket-events-trigger-queue.ts
> +          logger.info(this.queueName, "update transfer");
please add the after / before to the log so we can understand what has been updated. I would either turn it into an error log or make sure you create an alarm for the info log. otherwise, it might be hard to track if its actually happening

2023-07-17 19:30 UTC, nofir approved these changes

2023-07-17 19:30 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/transfer-websocket-events-trigger-job.ts
> +        if (data.before) {
why do we need the if (data.before)?

2023-07-17 19:37 UTC, nofir requested changes

2023-07-17 19:37 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/transfer-websocket-events-trigger-job.ts
> +        if (data.before) {
Also, maybe change the logic to only do it on update, here it will also trigger the log for when a transfer is deleted.

2023-07-17 20:02 UTC, tv3636 commented on packages/indexer/src/jobs/websocket-events/transfer-websocket-events-trigger-job.ts
> +        if (data.before) {
not sure about `if (data.before)` to be honest, copied that from [the PR to enable changed on tokens](https://github.com/reservoirprotocol/indexer/pull/5432/files#diff-a6beb83a9d20261ef8a99b15b515c346fffdf46b153465ce30dfaa0e6c6cda93R235)

2023-07-19 17:50 UTC, nofir approved these changes

2023-07-20 00:53 UTC, d3or approved these changes

2023-07-20 20:27 UTC, nofir submitted a review, later dismissed

2023-07-27 18:00 UTC, nofir requested changes

2023-07-27 18:00 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/transfer-websocket-events-trigger-job.ts
> +            );
i think we need to do a return here.

2023-07-27 18:12 UTC, nofir approved these changes

2023-07-27 18:54 UTC, tv3636 commented on packages/indexer/src/jobs/websocket-events/transfer-websocket-events-trigger-job.ts
> +            );
added the return

2023-07-27 20:11 UTC, nofir approved these changes

2023-07-28 15:10 UTC, merged