feat: Add sortDirection parameter
reservoirprotocol/indexer pull request #5633
Opened 2023-07-18 17:45 UTC by r3lays

2023-07-18 17:51 UTC, r3lays commented
Waiting for confirmation that the `updated_at` index presumably supports the sortDirection for both `asc` and `desc`

2023-07-20 13:36 UTC, ipeleg requested changes

2023-07-20 13:36 UTC, ipeleg commented on packages/indexer/src/api/endpoints/transfers/get-transfers-bulk/v1.ts
> +            nft_transfer_events.updated_at ASC,
instead of the if you can inject the query.sortDirection into the string

```
baseQuery += `
          ORDER BY
            nft_transfer_events.updated_at ${query.sortDirection},
            nft_transfer_events.address ${query.sortDirection},
            nft_transfer_events.token_id ${query.sortDirection}
        `
```

2023-07-20 13:36 UTC, ipeleg commented on packages/indexer/src/api/endpoints/transfers/get-transfers-bulk/v1.ts
Need also to update the continuation constructing in this line
https://github.com/reservoirprotocol/indexer/blob/main/packages/indexer/src/api/endpoints/transfers/get-transfers-bulk/v1.ts#L165

in a similar way to what is being done here
https://github.com/reservoirprotocol/indexer/blob/77d9f0a8daee50d0ed3cb95748b23ed270093b9c/packages/indexer/src/api/endpoints/tokens/get-tokens/v4.ts#L303

2023-07-20 13:38 UTC, ipeleg commented
@r3lays and if we're already at it, let's add the same logic to GET /transfers/v3

2023-07-26 15:34 UTC, ipeleg submitted a review, later dismissed

2023-07-27 18:40 UTC, ipeleg approved these changes

2023-07-27 18:40 UTC, merged