feat: use cdc event data for sale websocket
reservoirprotocol/indexer pull request #5666
Opened 2023-07-20 23:15 UTC by tv3636

2023-07-21 01:32 UTC, nofir requested changes

2023-07-21 01:32 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/sale-websocket-events-trigger-job.ts
>          FROM fill_events_2
i dont think you need to query the fill_events_2 table. just the currencies and tokens

2023-07-21 02:21 UTC, tv3636 commented on packages/indexer/src/jobs/websocket-events/sale-websocket-events-trigger-job.ts
>          FROM fill_events_2
thanks, actually don't need currencies either, not sure why we were getting `decimals` since it's not used. updated the query and types

2023-07-25 16:17 UTC, nofir approved these changes

2023-07-25 19:50 UTC, d3or approved these changes

2023-07-25 20:27 UTC, merged