feat: use cdc event data for token ws
reservoirprotocol/indexer pull request #5667
Opened 2023-07-20 23:27 UTC by tv3636

2023-07-21 01:24 UTC, nofir requested changes

2023-07-21 01:24 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/token-websocket-events-trigger-queue.ts
>          FROM tokens t
Why is tokens table needed here? can't you use the collection_id that you get from event to just query the collections table?

2023-07-21 01:24 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/token-websocket-events-trigger-queue.ts
>          FROM tokens t
if the collection_id is null just query the contracts table

2023-07-21 01:24 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/token-websocket-events-trigger-queue.ts
> +        const contract = fromBuffer(data.after.contract);
just to confirm, you get it as a buffer from the cdc event?

2023-07-21 02:26 UTC, tv3636 commented on packages/indexer/src/jobs/websocket-events/token-websocket-events-trigger-queue.ts
> +        const contract = fromBuffer(data.after.contract);
it would be a string, will fix

2023-07-25 16:02 UTC, nofir requested changes

2023-07-25 16:02 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/token-websocket-events-trigger-queue.ts
> +        const baseQuery = `
Potentially, there could be multiple collections with different images on the contract so i would do this:
1. check if the token has collecction_id (you get it from the cdc), if it does, query by contract and collection id (or just collection id)
2. otherwise, just query by contract (like you are doing now)

2023-07-25 16:15 UTC, tv3636 commented on packages/indexer/src/jobs/websocket-events/token-websocket-events-trigger-queue.ts
> +        const baseQuery = `
added a condition to check collection id if it exists on `data.after`

2023-07-25 16:19 UTC, nofir approved these changes

2023-07-25 19:50 UTC, d3or approved these changes

2023-07-26 15:36 UTC, merged