fix: sort by tx and filter out ens + uniswap mints
reservoirprotocol/indexer pull request #5692
Opened 2023-07-24 16:14 UTC by lunarmayor

2023-07-27 20:10 UTC, nofir requested changes

2023-07-27 20:10 UTC, nofir commented on packages/indexer/src/elasticsearch/indexes/activities/index.ts
> +const trendingBlocklist = [
if its only relevant for eth mainnet, maybe have it in the network settings for the index:
https://github.com/reservoirprotocol/indexer/blob/8b624d6a6a4c33e6c850e4e3c43f13e795607d49/packages/indexer/src/config/network.ts#L199

2023-08-10 15:16 UTC, lunarmayor commented on packages/indexer/src/elasticsearch/indexes/activities/index.ts
> +const trendingBlocklist = [
sorry took a bit but made the change

2023-08-14 19:40 UTC, lunarmayor commented on packages/indexer/src/elasticsearch/indexes/activities/index.ts
> +const trendingBlocklist = [
@nofir good to merge?

2023-08-14 19:41 UTC, nofir approved these changes

2023-08-14 20:20 UTC, nofir commented on packages/indexer/src/elasticsearch/indexes/activities/index.ts
> +const trendingBlocklist = [
approved

2023-08-15 20:40 UTC, merged