feat: add creator and token count to tokens API
reservoirprotocol/indexer pull request #5947
Opened 2023-08-10 18:56 UTC by tv3636

2023-08-10 19:12 UTC, nofir requested changes

2023-08-10 19:12 UTC, nofir commented on packages/indexer/src/api/endpoints/tokens/get-tokens/v6.ts
> +            creator: r.creator ? fromBuffer(r.creator) : null,
this should be on the collection obj

2023-08-10 19:12 UTC, nofir commented on packages/indexer/src/api/endpoints/tokens/get-tokens/v6.ts
> +            tokenCount: r.token_count,
this should be on the collection obj

2023-08-14 19:36 UTC, nofir requested changes

2023-08-14 19:36 UTC, nofir commented on packages/indexer/src/api/endpoints/tokens/get-tokens/v6.ts
> +              creator: Joi.string().lowercase().pattern(regex.address).required(),
why is there required()? also, should allow null

2023-08-14 19:53 UTC, tv3636 commented on packages/indexer/src/api/endpoints/tokens/get-tokens/v6.ts
> +              creator: Joi.string().lowercase().pattern(regex.address).required(),
yeah not sure, fixed

2023-08-14 20:21 UTC, nofir approved these changes

2023-08-16 15:24 UTC, merged