feat: add collectionNewContractDeployedJob
reservoirprotocol/indexer pull request #6166
Opened 2023-09-01 03:59 UTC by d3or

2023-09-01 19:05 UTC, nofir commented on packages/indexer/src/jobs/collections/collection-contract-deployed.ts
> +      case "ERC721":
What about ERC721C that was added for the payment processor protocol?

2023-09-01 19:05 UTC, nofir commented on packages/indexer/src/jobs/collections/collection-contract-deployed.ts
> +    if (!contract || !deployer) {
Why is this an OR? isn't the contract required for the logic?

2023-09-01 19:05 UTC, nofir commented on packages/indexer/src/jobs/collections/collection-contract-deployed.ts
> +              INSERT INTO collections (
What would happen when the first token is minted? today we have to logic to create the collection once we get the collection metadata, would that not happen anymore?

2023-09-05 12:23 UTC, d3or commented on packages/indexer/src/jobs/collections/collection-contract-deployed.ts
> +      case "ERC721":
Every ERC-721 (nft) compliant contract must implment ERC721 and ERC165 interfaces, which can be checked via the identifier `0x80ac58cd`

More info here: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md#specification

2023-09-05 12:26 UTC, d3or commented on packages/indexer/src/jobs/collections/collection-contract-deployed.ts
> +    if (!contract || !deployer) {
If either are missing that means that something is wrong with the trace / we are missing some data. Both contract and deployer should never be null

2023-09-05 12:29 UTC, d3or commented on packages/indexer/src/jobs/collections/collection-contract-deployed.ts
> +              INSERT INTO collections (
We should still keep that for now. Once this goes live there will be collections that have already been deployed but have no mints yet, which we wont catch with this job and its only being called from real time.

2023-09-05 14:09 UTC, georgeroman commented on packages/indexer/src/jobs/collections/collection-contract-deployed.ts
> +          creator: deployer,
Same here, I assume `creator` is a `BYTEA`

2023-09-05 20:12 UTC, nofir submitted a review, later dismissed

2023-09-05 20:12 UTC, nofir commented on packages/indexer/src/jobs/token-updates/mint-queue-job.ts
> +      let isFirstToken = false;
probably can be inside the if

2023-09-06 17:39 UTC, nofir approved these changes

2023-09-11 16:47 UTC, nofir requested changes

2023-09-11 16:47 UTC, nofir commented on packages/indexer/src/jobs/collections/collection-contract-deployed.ts
> +          created_at: payload.blockTimestamp ? new Date(payload.blockTimestamp * 1000) : null,
i think created_at should always be the db insert timestamp and we should have another field to represent the contract deployment timestamp. i think it will be helpful especially if we do a backfill

2023-09-11 18:31 UTC, nofir approved these changes

2023-09-11 18:39 UTC, merged