Tv/platf 2051 unknown sources default to reservoirtools
reservoirprotocol/indexer pull request #6273
Opened 2023-09-12 19:57 UTC by tv3636

2023-09-18 13:56 UTC, nofir requested changes
in addition to the other comments, i think you missed the logic in the data export to dune, for example: 
https://github.com/reservoirprotocol/indexer/blob/fcf0f25cb8dd30214c35caf8326eaefefacec4f8/packages/indexer/src/jobs/data-export/data-sources/sales.ts#L68

2023-09-18 17:24 UTC, tv3636 commented on packages/indexer/src/models/sources/index.ts
> +  public getFullSourceObject(source: SourcesEntity | undefined): {
in that case we'll have duplicate logic across all the older APIs that use source but not through the common joi objects, is that ok?

2023-09-18 18:16 UTC, tv3636 commented on packages/indexer/src/models/sources/index.ts
> +    let sourceEntity: SourcesEntity | undefined;
just curious, if we're making this change across all APIs including older versions, when would we ever still want to use the default?

2023-09-20 16:49 UTC, nofir commented on packages/indexer/src/models/sources/index.ts
> +  public getFullSourceObject(source: SourcesEntity | undefined): {
we can't add the common joi object in old apis?

2023-09-20 16:55 UTC, nofir commented on packages/indexer/src/models/sources/index.ts
> +    let sourceEntity: SourcesEntity | undefined;
i don't think there is a usecase now but there might be one in the future (or we change our minds..)

2023-09-20 16:59 UTC, nofir requested changes

2023-09-20 16:59 UTC, nofir commented on packages/indexer/src/models/sources/index.ts
> +  public getFullSourceObject(source: SourcesEntity | undefined): {
you're already doing ```source: sources.getSourceObject(source),``` Im just saying that the method here should be on the joi class as they are dedicated per external formatting

2023-09-20 16:59 UTC, nofir commented on packages/indexer/src/jobs/data-export/data-sources/ask-events.ts
> +        source: sources.get(r.order_source_id_int)
instead of doing the get twice, just initialize a source param and do the iff with it (for all below files too)

2023-09-20 21:13 UTC, nofir commented on packages/indexer/src/api/endpoints/orders/get-orders-bids/v1.ts
> +            id: source?.address ?? null,
just to confirm, will it now return null instead of undefined (property wont be there)?

2023-09-20 21:13 UTC, nofir commented on packages/indexer/src/api/endpoints/sources/get-sources/v1.ts
> +            id: source.address ?? null,
why are the changes here needed?

2023-09-20 21:23 UTC, tv3636 commented on packages/indexer/src/api/endpoints/orders/get-orders-bids/v1.ts
> +            id: source?.address ?? null,
yes exactly

2023-09-20 21:24 UTC, tv3636 commented on packages/indexer/src/api/endpoints/sources/get-sources/v1.ts
> +            id: source.address ?? null,
for consistency i was updating anywhere we return source to default to null rather than undefined, but if this case is separate i can undo the change

2023-09-20 22:29 UTC, nofir commented on packages/indexer/src/api/endpoints/sources/get-sources/v1.ts
> +            id: source.address ?? null,
I dont think you need to make any changes here

2023-09-20 22:29 UTC, nofir commented on packages/indexer/src/api/endpoints/orders/get-orders-bids/v1.ts
> +            id: source?.address ?? null,
remind me, why are we doing it?

2023-09-22 15:42 UTC, nofir submitted a review, later dismissed

2023-09-28 15:04 UTC, nofir submitted a review, later dismissed

2023-10-04 16:41 UTC, nofir approved these changes

2023-10-04 16:55 UTC, merged