Index ERC20 Bedenia
reservoirprotocol/indexer pull request #6312
Opened 2023-09-15 23:47 UTC by nicefacer

2023-09-16 00:50 UTC, nicefacer reviewed
Made the image 128x128

2023-09-18 13:36 UTC, nofir requested changes

2023-09-18 13:36 UTC, nofir commented on packages/indexer/src/config/network.ts
> +            "0x55818Be03e5103e74f96dF7343Dd1862A6d215f2",
@nicefacer can you change the address to be lowercase?

2023-09-18 15:22 UTC, nicefacer reviewed
Requested change done.

2023-09-18 15:23 UTC, nicefacer commented on packages/indexer/src/config/network.ts
> +            "0x55818Be03e5103e74f96dF7343Dd1862A6d215f2",
requested change done

2023-09-20 16:43 UTC, nofir approved these changes

2023-09-20 16:47 UTC, nofir requested changes

2023-09-20 16:47 UTC, nofir commented on packages/indexer/src/config/network.ts
> +              decimals: 8,
![Screenshot 2023-09-20 at 12 44 35 PM](https://github.com/reservoirprotocol/indexer/assets/42353301/06add489-0d51-4517-849b-c84590b91488)

Just confirming the number of decimals. otherwise looks ok

2023-09-20 16:54 UTC, nicefacer commented on packages/indexer/src/config/network.ts
> +              decimals: 8,
The BIdenia decimal is 8.


The image you shared is for Biden Token not BIdenia.

2023-09-20 17:09 UTC, merged