feat: add one minute cache to top selling endpoint
reservoirprotocol/indexer pull request #6418
Opened 2023-09-25 13:28 UTC by lunarmayor

@nofir trying to add a one-minute cache on this endpoint. would this work?

2023-10-02 19:02 UTC, lunarmayor commented
things i updated: 
- cache collections after fetching them and keep them up to date with the change events
- increase the limit to 1000 
- improve the speed of and weight of the cache job for the windows
- move the endpoint over to be a dedicated trending collections endpoint
- added cache header for 1m

2023-10-03 14:49 UTC, lunarmayor commented on packages/indexer/src/api/endpoints/collections/get-trending-collections/v1.ts
> +        .description("Amount of items returned in response. Default is 25 and max is 50"),
update to use show max 1000

2023-10-03 17:35 UTC, pedromcunha requested changes

2023-10-03 17:35 UTC, pedromcunha commented on packages/indexer/src/api/endpoints/collections/get-trending-collections/v1.ts
> +      logger.error(`get-top-selling-collections-${version}-handler`, `Handler failure: ${error}`);
should we change this so that it reflects the api function name?

2023-10-03 17:35 UTC, pedromcunha commented on packages/indexer/src/api/endpoints/collections/get-trending-collections/v1.ts
> +        `get-top-selling-collections-${version}-handler`,
Same here re the name

2023-10-03 17:35 UTC, pedromcunha commented on packages/indexer/src/api/endpoints/collections/get-trending-collections/v1.ts
> +    "top-selling-collections",
name change probably required

2023-10-03 17:35 UTC, pedromcunha commented on packages/indexer/src/api/endpoints/collections/get-trending-collections/v1.ts
> +      "top-selling-collections",
name change

2023-10-03 17:35 UTC, pedromcunha commented on packages/indexer/src/api/endpoints/collections/get-top-selling-collections/v2.ts
>      privacy: "public",
we should deprecate this api

2023-10-03 17:35 UTC, pedromcunha commented on packages/indexer/src/jobs/top-selling-collections-cache/index.ts
> +  try {
should we also check if doBackgroundWork is enabled?

2023-10-03 17:35 UTC, pedromcunha commented on packages/indexer/src/models/top-selling-collections/top-selling-collections.ts
> +          limit: 1000,
There's a param in the trending api for the limit, is it supposed to be passed into here and used?

2023-10-03 17:39 UTC, lunarmayor commented on packages/indexer/src/api/endpoints/collections/get-top-selling-collections/v2.ts
>      privacy: "public",
yah we should i think

2023-10-03 17:39 UTC, lunarmayor commented on packages/indexer/src/api/endpoints/collections/get-trending-collections/v1.ts
> +      logger.error(`get-top-selling-collections-${version}-handler`, `Handler failure: ${error}`);
yah definitely

2023-10-03 17:41 UTC, lunarmayor commented on packages/indexer/src/jobs/top-selling-collections-cache/index.ts
> +  try {
it gets checked below so I don't think so. basically pulled this out to make it easier to immediately call once

2023-10-03 17:42 UTC, lunarmayor commented on packages/indexer/src/models/top-selling-collections/top-selling-collections.ts
> +          limit: 1000,
this is the job so it needs to get the maximum limit that could be returned from the cache

2023-10-05 16:08 UTC, lunarmayor commented
@pedromcunha @nofir addressed comments and fixed the conflicts

2023-10-05 17:05 UTC, nofir commented on packages/indexer/src/jobs/cdc/topics/indexer-collections.ts
> +    await redis.set(`collectionCache:v1:${payload.after.id}`, JSON.stringify(payload.after), "XX");
our naming convention is using dashes vs camelcase

2023-10-05 17:05 UTC, nofir commented on packages/indexer/src/api/endpoints/collections/get-trending-collections/v1.ts
> +  const collectionMetadataCache = await redis
did you test it with 1000 (the previous limit was 50) i worry a bit about blocking redis. is it possible to do in the background job?
or maybe we can lower the limit and introduce pagination

2023-10-05 18:10 UTC, lunarmayor commented on packages/indexer/src/api/endpoints/collections/get-trending-collections/v1.ts
> +  const collectionMetadataCache = await redis
think saving 1000 is going to happen very infrequently. maybe only the first time. Doesn't seem to be a problem from my testing

2023-10-05 18:10 UTC, lunarmayor commented on packages/indexer/src/jobs/cdc/topics/indexer-collections.ts
> +    await redis.set(`collectionCache:v1:${payload.after.id}`, JSON.stringify(payload.after), "XX");
okay can update

2023-10-05 18:17 UTC, lunarmayor commented on packages/indexer/src/api/endpoints/collections/get-trending-collections/v1.ts
> +  const collectionMetadataCache = await redis
reason to return 1000 is ME does client-side filtering and sorting for their trending collections so they need quite a bit to work with. this avoids needing to add a bunch of filtering options for this endpoint

2023-10-08 21:39 UTC, nofir commented on packages/indexer/src/api/endpoints/collections/get-trending-collections/v1.ts
> +  const collectionMetadataCache = await redis
so there is no plan to support for continuation right now? its always 1000?

1. maybe we can make the max 1000 and the default 50? 
2. you can change the logic to get / save from redis in smaller batches, while still supporting 1000 at the end

we rely on redis less now since we switched to rabbitmq so its less of an issue but its something to be aware of

2023-10-09 14:52 UTC, lunarmayor commented on packages/indexer/src/api/endpoints/collections/get-trending-collections/v1.ts
> +  const collectionMetadataCache = await redis
yah can do both. For ME we really want them mostly hitting the cdn so it's possible that we would want to make it always 1000. Think it would be fine to set the default to 50 though also

2023-10-10 16:35 UTC, nofir commented on packages/indexer/src/api/endpoints/collections/get-trending-collections/v1.ts
> +      const redisMulti = redis.multi(batch as any);
so this will make (potentially) 2 blocking multi calls with 1000 commands (set and expire per collection) in each?

2023-10-10 16:35 UTC, nofir commented on packages/indexer/src/api/endpoints/collections/get-trending-collections/v1.ts
> +    collectionsResult = await getTopSellingCollections({
aren't you missing caching the result once its retrieved from es?

2023-10-10 16:37 UTC, lunarmayor commented on packages/indexer/src/api/endpoints/collections/get-trending-collections/v1.ts
> +    collectionsResult = await getTopSellingCollections({
in this case, it's just using the pre-calculated cache. hopefully people move away from this endpoint in general

2023-10-10 16:39 UTC, lunarmayor commented on packages/indexer/src/api/endpoints/collections/get-trending-collections/v1.ts
> +      const redisMulti = redis.multi(batch as any);
it will be 500 commands at a time because of the flat map. so if there is 1000 collections it's going to break into 4 batches of 500 commands (set and expire)

2023-10-10 16:40 UTC, lunarmayor commented on packages/indexer/src/api/endpoints/collections/get-trending-collections/v1.ts
> +      const redisMulti = redis.multi(batch as any);
it's a little hard to say what the right batch size is but figure this this is better than trying to run 2000 commands

2023-10-10 16:41 UTC, nofir commented on packages/indexer/src/api/endpoints/collections/get-trending-collections/v1.ts
> +    collectionsResult = await getTopSellingCollections({
but this is the new endpoint - "get-trending-collections/v1" ? im confused...

2023-10-10 16:41 UTC, nofir commented on packages/indexer/src/api/endpoints/collections/get-trending-collections/v1.ts
> +    collectionsResult = await getTopSellingCollections({
So in the new impl, we never cache the result from es?

2023-10-10 20:08 UTC, nofir approved these changes

2023-10-11 14:53 UTC, merged