Tv/platf 2283 return fill source as well as order source in the activity
reservoirprotocol/indexer pull request #6465
Opened 2023-09-26 15:54 UTC by tv3636

2023-09-26 20:53 UTC, nofir requested changes

2023-09-26 20:53 UTC, nofir commented on packages/indexer/src/api/endpoints/activities/get-token-activity/v5.ts
> +        const fillSource = activity.event?.fillSourceId
does it make sense to wait for the pr for the default source? that way you can use the same logic

2023-09-26 20:53 UTC, nofir commented on packages/indexer/src/elasticsearch/indexes/activities/base/index.ts
> +  fill_source_id?: number;
can this be event_fill_source_id?

2023-09-26 20:53 UTC, nofir commented on packages/indexer/src/elasticsearch/indexes/activities/base/index.ts
> +            fillSourceId: data.fill_source_id,
event_fill_source_id

2023-09-26 20:53 UTC, nofir commented on packages/indexer/src/elasticsearch/indexes/activities/event-handlers/fill-event-created/index.ts
> +                  fill_source_id,
event_fill_source_id

2023-09-26 21:15 UTC, tv3636 commented on packages/indexer/src/api/endpoints/activities/get-token-activity/v5.ts
> +        const fillSource = activity.event?.fillSourceId
don't we actually not want to use it here since we'd have `fillSource: null` on non-sale events?

2023-09-27 16:08 UTC, nofir approved these changes

2023-10-02 16:50 UTC, nofir approved these changes

2023-10-03 18:29 UTC, merged