feat: allow filter on fill/order source for sales ws
reservoirprotocol/indexer pull request #6531
Opened 2023-10-04 20:54 UTC by tv3636

2023-10-05 16:55 UTC, nofir requested changes

2023-10-05 16:55 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/sale-websocket-events-trigger-job.ts
> +          fillSource: result.fillSource ?? "",
Isnt the fillSource / orderSource the whole obj? it should be based on the domain

2023-10-05 17:03 UTC, tv3636 commented on packages/indexer/src/jobs/websocket-events/sale-websocket-events-trigger-job.ts
> +          fillSource: result.fillSource ?? "",
`getJoiSaleObject` returns just the domain: https://github.com/reservoirprotocol/indexer/blob/8dd3a14d4e16bdd0fb254e48b17b23ad928decae/packages/indexer/src/common/joi.ts#L909

2023-10-05 17:16 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/sale-websocket-events-trigger-job.ts
> +          fillSource: result.fillSource ?? "",
i missed that, ok makes sense. any reason to set it to ""? just trying to understand if not including it (undefined), creates an issues?

2023-10-05 17:23 UTC, tv3636 commented on packages/indexer/src/jobs/websocket-events/sale-websocket-events-trigger-job.ts
> +          fillSource: result.fillSource ?? "",
the ws publisher expects all tags to be `string`, alternatively we could allow the tags to be null and remove the empty string here

2023-10-06 13:52 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/sale-websocket-events-trigger-job.ts
> +          fillSource: result.fillSource ?? "",
and again, if the firehose, just ignores empty strings, its probably ok to keep like that, i just thought it was cleaner

2023-10-10 16:08 UTC, nofir approved these changes

2023-10-10 16:15 UTC, merged