feat: support token name search by id
reservoirprotocol/indexer pull request #6532
Opened 2023-10-04 21:19 UTC by tv3636

2023-10-05 16:53 UTC, nofir requested changes

2023-10-05 16:53 UTC, nofir commented on packages/indexer/src/api/endpoints/tokens/get-tokens/v6.ts
> +        if (!isNaN(query.tokenName)) {
not sure this was the intention. basically if in the db the token name is missing , search the token id , with whatever was passed from the client. see bored ape for example (no token name)

2023-10-05 17:07 UTC, tv3636 commented on packages/indexer/src/api/endpoints/tokens/get-tokens/v6.ts
> +        if (!isNaN(query.tokenName)) {
so we'd have 2 queries then? i think it makes sense to do it at once since it's pretty common for token names to have the tokenId and the response will be faster

2023-10-05 17:14 UTC, nofir requested changes

2023-10-05 17:14 UTC, nofir commented on packages/indexer/src/api/endpoints/tokens/get-tokens/v6.ts
> +        if (!isNaN(query.tokenName)) {
but the tokenName being passed from the client is not going to be null. today if you pass "1" when you search for bored apes, you would not get results, right? (because the name in the db is null)

wouldn't you be able to do:
```conditions.push(`COALESCE (t.name,t.token_id) ILIKE $/tokenName/`);```

maybe im missing something

2023-10-05 17:26 UTC, tv3636 commented on packages/indexer/src/api/endpoints/tokens/get-tokens/v6.ts
> +        if (!isNaN(query.tokenName)) {
`!isNaN(query.tokenName)` evaluates to true if the string is a valid number (and we already checked above for `query.tokenName` not being null, so in cases where the search string is a number, we would also check the tokenId for matches

2023-10-06 13:45 UTC, nofir requested changes

2023-10-06 13:45 UTC, nofir commented on packages/indexer/src/api/endpoints/tokens/get-tokens/v6.ts
> +        if (!isNaN(query.tokenName)) {
if you're going with this approach of checking both, i would change the token id compare to equal. i dont think we want to do a LIKE , you dont want to get 111 token if someone is looking for 1

2023-10-06 18:59 UTC, nofir approved these changes

2023-10-06 19:16 UTC, merged