Armando/grwth 3385 trending mints api endpoint
reservoirprotocol/indexer pull request #6875
Opened 2023-11-02 21:29 UTC by r3lays

2023-11-03 20:01 UTC, nofir requested changes

2023-11-06 15:40 UTC, r3lays commented on packages/indexer/src/api/endpoints/collections/get-trending-mints/v1.ts
> +export interface MintResult {
Are you referring to the version or the sources? 
The "version" is used in the handler log statements & the "Sources" is used on line 328 to get the source for the floor ask.

2023-11-07 20:54 UTC, r3lays commented on packages/indexer/src/api/endpoints/collections/get-trending-mints/v1.ts
> +  const collectionsToFetch = collectionIds.map((id: string) => `collection-cache:v1:${id}`);
I merged the two functions together.
Have to discuss with Michael re the caching logic.

2023-11-07 20:54 UTC, r3lays commented on packages/indexer/src/api/endpoints/collections/get-trending-mints/v1.ts
> +      c.non_flagged_floor_sell_id,
Gonna bring this up to Michael as well.

2023-11-13 18:39 UTC, lunarmayor submitted a review, later dismissed

2023-11-13 20:05 UTC, nofir requested changes

2023-11-13 20:05 UTC, nofir commented on packages/indexer/src/api/routes.ts
> +    path: "/collections/get-trending-mints/v1",
should be (to follow the same pattern):
/collections/trending-mints/v1

2023-11-13 20:05 UTC, nofir commented on packages/indexer/src/api/endpoints/collections/get-trending-mints/v1.ts
> +async function formatCollections(
can this use the formatCollections from the trending and add the mint data? if not, its fine.

2023-11-13 20:05 UTC, nofir commented on packages/indexer/src/api/endpoints/collections/get-trending-mints/v1.ts
> +      const elasticMintData = await getTrendingMints({
I would have a check here on mintingCollections.length to make sure we don't call es for nothing

2023-11-13 20:27 UTC, nofir approved these changes

2023-11-13 20:35 UTC, merged