deor/platf 2243 add image version updated at
reservoirprotocol/indexer pull request #7024
Opened 2023-11-20 15:19 UTC by d3or

- feat: remove any
- feat: rename jobs & add to job list
- feat: if no token uri, write plain metadata
- feat: use onchain indexing for tokens that have slug
- feat: update add to uri queue logic
- feat: add onchain to get-provider-metadata
- feat: fix calling wrong method, not extending
- feat: add better handling for onchain edge cases
- feat: default to token id as name
- feat: add endpoint to increment cache version
- feat: fall back to simplehash
- feat: add metadata index process job when fallback
- feat: cleanup
- feat: rename to image_version_updated_at
- feat: remove to buffer on collection id
- feat: fix route
- feat: rename image_version_updated_at
- feat: only fallback to simplehash if fallbackTokens is not empty
- feat: remove comments
- feat: fix comments, add fallbackMetadataIndexingMethod
- feat: update apis to use image_version_upated_at

2023-11-20 18:51 UTC, nofir requested changes

2023-11-20 18:51 UTC, nofir commented on packages/indexer/src/api/endpoints/admin/post-update-image-version.ts
> +            SET image_version_updated_at = NOW()
you need to set the updated_at=now()

2023-11-20 18:51 UTC, nofir commented on packages/indexer/src/api/endpoints/admin/post-update-image-version.ts
> +      await idb.oneOrNone(
tbh, i would remove it right now and just leave the logic to update a specific token or get the collection from the db and check the token count and if < 10k, allow it. otherwise we can have weird complaints that only some of the token images were invalidated. (we can add an admin api to allow to do it on any collections, similar to the refresh metadata)

2023-11-20 18:51 UTC, nofir commented on packages/indexer/src/api/endpoints/admin/post-update-image-version.ts
> +          SET image_version_updated_at = NOW()
you need to set the updated_at=now()

2023-11-20 18:51 UTC, nofir commented on packages/indexer/src/api/endpoints/orders/get-user-top-bids/v1.ts
> +            SELECT t.token_id, t.image_version_updated_at, t.name, t.image, t.collection_id, floor_sell_value AS "token_floor_sell_value", last_sell_value AS "token_last_sell_value"
this is really not an issue but i realize "image_version_updated_at" is a bit confusing as there is not image version, the timestamp is the version. probably ok to leave as is but a better name would probably be `image_version` which is the timestamp. 

Again, we can ship it as is and it will be fine.

2023-11-20 18:51 UTC, nofir commented on packages/indexer/src/api/endpoints/transfers/get-sales/v4.ts
> +
redundant space

2023-11-20 18:51 UTC, nofir commented on packages/indexer/src/utils/assets.ts
>      return assets;
Is the getLocalAssetsLink still being used at all? does it even make sense to keep it (and migrate everywhere to use  getResizedImageUrl)?

2023-11-20 20:04 UTC, d3or commented on packages/indexer/src/utils/assets.ts
>      return assets;
getLocalAssetsLink is used when we are dealing with an array of images/sample images

2023-11-20 20:24 UTC, nofir submitted a review, later dismissed

2023-11-20 20:46 UTC, nofir requested changes

2023-11-20 20:46 UTC, nofir commented on packages/indexer/src/utils/assets.ts
>      return assets;
i think we can still get rid of it but its not a priority for now

2023-11-20 20:46 UTC, nofir commented on packages/indexer/src/api/endpoints/activities/get-collection-activity/v6.ts
> +                      image_version: tokenResult.image_version,
you are missing the cdc logic:
https://github.com/reservoirprotocol/indexer/blob/96be7513f57844350cd2aa80f506942b012b2438/packages/indexer/src/jobs/cdc/topics/indexer-tokens.ts#L48

2023-11-21 01:55 UTC, nofir approved these changes

2023-11-21 01:55 UTC, nofir commented on packages/indexer/src/jobs/cdc/topics/indexer-tokens.ts
> +            ? Math.floor(new Date(payload.after.image_version).getTime() / 1000)
do you still need to do that? (you are doing it in the signImage on line 108)?

2023-11-21 16:15 UTC, nofir submitted a review, later dismissed

2023-11-21 16:40 UTC, nofir approved these changes

2023-11-21 16:43 UTC, merged