feat: update collection image size
reservoirprotocol/indexer pull request #7101
Opened 2023-11-27 18:20 UTC by d3or

2023-11-29 22:00 UTC, nofir requested changes

2023-11-29 22:00 UTC, nofir commented on packages/indexer/src/api/endpoints/activities/get-collection-activity/v6.ts
> +          LEFT JOIN collections
We actually need to update the activities index to include collection_image_version. We need to make sure the following:
- the activities jobs need to support updating the collection_image_version
- we need to trigger a refresh of the activity collection when the collection_image_version changes.

2023-12-06 19:16 UTC, nofir requested changes

2023-12-06 19:16 UTC, nofir commented on packages/indexer/src/utils/assets.ts
> +  public static getLocalAssetsLink(
Why do we need "getLocalAssetsLink"? Can't we use the same getResizedImageUrl method? or change it to call the getResizedImageUrl?

2023-12-06 19:16 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/token-websocket-events-trigger-job.ts
> +                  ? Assets.getResizedImageUrl(r.collection_image, ImageSize.small)
why small? shouldn't it be medium?

2023-12-06 19:16 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/token-websocket-events-trigger-job.ts
> +                  ? Assets.getResizedImageUrl(r.collection_image, ImageSize.small)
why small? shouldn't it be medium?

2023-12-06 21:00 UTC, d3or commented on packages/indexer/src/utils/assets.ts
> +  public static getLocalAssetsLink(
its called in around ~20 different places when we are creating an array of images (sample images) usually.

2023-12-14 20:26 UTC, nofir approved these changes

2023-12-18 15:33 UTC, nofir approved these changes

2023-12-18 19:58 UTC, merged