feat: add Reddit community tokens
reservoirprotocol/indexer pull request #7112
Opened 2023-11-28 15:02 UTC by WarmBeer

I would like to add these Reddit community tokens (All ERC-20 tokens on Polygons) so that I can support them on the [RCAX Reddit Avatar Marketplace](https://marketplace.rcax.io).

2023-12-15 09:26 UTC, WarmBeer commented
Reminder 😁

2023-12-18 19:21 UTC, nofir requested changes

2023-12-18 19:21 UTC, nofir commented on packages/indexer/src/config/network.ts
> +            "0xc6268A296c810024aa3AA2F5Cc2c255bF995AA44",
all address values need to be in lowercase

2023-12-18 19:33 UTC, WarmBeer commented on packages/indexer/src/config/network.ts
> +            "0xc6268A296c810024aa3AA2F5Cc2c255bF995AA44",
Updated now. Thank you for reviewing!

2023-12-18 19:35 UTC, nofir approved these changes

2023-12-18 19:35 UTC, merged