feat: add migration
reservoirprotocol/indexer pull request #7341
Opened 2023-12-14 18:42 UTC by d3or

2023-12-14 18:43 UTC, georgeroman commented on packages/indexer/src/migrations/17025792250000_fill_events_kind.sql
> +ALTER TYPE "fill_events_2" ADD COLUMN "kind" TEXT;
I think `TEXT` is wasteful vs using an enum as we do in other places like `order_type_t`.

2023-12-14 18:44 UTC, nofir requested changes

2023-12-14 18:44 UTC, nofir commented on packages/indexer/src/migrations/17025792250000_fill_events_kind.sql
> +ALTER TYPE "fill_events_2" ADD COLUMN "kind" TEXT;
we usually create an enum:
```
CREATE TYPE "order_kind_t" AS ENUM (
  'wyvern-v2',
  'wyvern-v2.3',
  'looks-rare',
  'opendao-erc721',
  'opendao-erc1155',
  'zeroex-v4-erc721',
  'zeroex-v4-erc1155',
  'foundation',
  'x2y2',
  'seaport'
)
```;

2023-12-14 18:56 UTC, georgeroman commented on packages/indexer/src/migrations/17025792250000_fill_events_kind.sql
> +CREATE TYPE "fill_event_kind" AS ENUM (
Do we really need transfer and sale here? Maybe for efficiency we can represent transfers as null (no need to backfill) while for sales from previous experience that's very hard to associate.

2023-12-15 20:05 UTC, nofir submitted a review, later dismissed

2023-12-19 21:17 UTC, nofir submitted a review, later dismissed

2023-12-20 16:26 UTC, georgeroman approved these changes

2024-01-09 17:50 UTC, merged