Update network.ts
reservoirprotocol/indexer pull request #7393
Opened 2023-12-18 00:38 UTC by dturska12

# Pull Request Template

Request support for $AURA token

## Database Migration Strategy

For tables such as `orders`, `tokens`, `collections`, etc., we split the deployment into two distinct phases:

1. **PR for Applying Migration Changes:**

   - This PR should solely focus on the database schema changes.
   - Ensure that the migration script is thoroughly tested and is backward compatible.

2. **PR for Applying Code Changes:**
   - This PR should include the code changes that utilize the new database schema.
   - Make sure to handle any new database schema elements within the code.

## Handling New Columns with Default Values

When adding new columns with a default value, follow this approach:

- **Initial Migration Without a Default Value:**

  - Perform the initial migration without setting a default value for the new column.
  - Ensure that the application code is equipped to handle the absence of a default value.

- **Code Modifications:**
  - Adapt the application code to manage the logic around the new column.
  - Once the code is deployed and stable, a subsequent migration can introduce the default value if necessary.

## Additional Notes

Include any additional information that you believe is important for the reviewers to know.

2023-12-18 19:20 UTC, nofir requested changes

2023-12-18 19:20 UTC, nofir commented on packages/indexer/src/config/network.ts
> +            "0x2bff8ddbc1F13F6F976a8f4d7feE677272fB6e0e",
need to be lowercase (also the contract below)

2023-12-18 20:26 UTC, dturska12 commented on packages/indexer/src/config/network.ts
> +            "0x2bff8ddbc1F13F6F976a8f4d7feE677272fB6e0e",
ah sorry completely forgot about that. Have updated the address

2023-12-19 13:56 UTC, nofir approved these changes

2023-12-19 13:57 UTC, merged