feat: pending tx ws
reservoirprotocol/indexer pull request #7814
Opened 2024-01-24 05:24 UTC by lljxx1

# Pull Request Template

## Database Migration Strategy

For tables such as `orders`, `tokens`, `collections`, etc., we split the deployment into two distinct phases:

1. **PR for Applying Migration Changes:**

   - This PR should solely focus on the database schema changes.
   - Ensure that the migration script is thoroughly tested and is backward compatible.

2. **PR for Applying Code Changes:**
   - This PR should include the code changes that utilize the new database schema.
   - Make sure to handle any new database schema elements within the code.

## Handling New Columns with Default Values

When adding new columns with a default value, follow this approach:

- **Initial Migration Without a Default Value:**

  - Perform the initial migration without setting a default value for the new column.
  - Ensure that the application code is equipped to handle the absence of a default value.

- **Code Modifications:**
  - Adapt the application code to manage the logic around the new column.
  - Once the code is deployed and stable, a subsequent migration can introduce the default value if necessary.

## Additional Notes

Include any additional information that you believe is important for the reviewers to know.

2024-01-25 14:33 UTC, nofir requested changes

2024-01-25 14:33 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/utils.ts
> +export async function getTokenMetadata(tokenId: string, contract: string) {
Is there a reason to create a new method and not use [this](https://github.com/reservoirprotocol/indexer/blob/9965b8b1b7f0f6f7ffc242f5fd7297afadb8dd0e/packages/indexer/src/models/tokens/index.ts#L27)?

2024-01-25 14:33 UTC, nofir commented on packages/indexer/src/tests/pending-state/pending.test.ts
> +      // console.log("recent", recent);
please remove comment

2024-01-25 14:33 UTC, nofir commented on packages/indexer/src/jobs/websocket-events/utils.ts
> +export async function getTokenMetadata(tokenId: string, contract: string) {
Might be simpler with the mocking but if not, then i would just use the existing one

2024-01-25 16:04 UTC, nofir submitted a review, later dismissed

2024-01-25 17:20 UTC, ipeleg submitted a review, later dismissed

2024-01-28 14:03 UTC, georgeroman commented
@nofir or @ipeleg Asking for on last round of review before merging this

2024-01-29 14:07 UTC, ipeleg approved these changes

2024-02-01 18:26 UTC, merged