Jaden/platf 3319 fr getusertokens api addition
reservoirprotocol/indexer pull request #8283
Opened 2024-03-12 02:21 UTC by JadenDurnford

2024-03-12 17:37 UTC, nofir requested changes

2024-03-12 17:37 UTC, nofir commented on packages/indexer/src/api/endpoints/tokens/get-user-tokens/v10.ts
> +               c.name as collection_name, c.token_count as collection_token_count, con.kind, con.symbol, extract(epoch from con.deployed_at) AS contract_deployed_at, c.metadata, c.royalties, (c.metad
remind me, any reason to do `extract(epoch`?

2024-03-12 17:37 UTC, nofir commented on packages/indexer/src/api/endpoints/tokens/get-user-tokens/v10.ts
> +               c.name as collection_name, c.token_count as collection_token_count, con.kind, con.symbol, extract(epoch from con.deployed_at) AS contract_deployed_at, c.metadata, c.royalties, (c.metad
I think you can just return con.deployed_at and then skip the * 1000 in line 1045

2024-03-12 17:37 UTC, nofir commented on packages/indexer/src/api/endpoints/tokens/get-user-tokens/v10.ts
> +                tokenCount: String(r.collection_token_count),
do we return it as string in the collections / user collections api?

2024-03-12 17:47 UTC, JadenDurnford commented on packages/indexer/src/api/endpoints/tokens/get-user-tokens/v10.ts
> +               c.name as collection_name, c.token_count as collection_token_count, con.kind, con.symbol, extract(epoch from con.deployed_at) AS contract_deployed_at, c.metadata, c.royalties, (c.metad
I copied the logic from collections v7: https://github.com/reservoirprotocol/indexer/blob/de3a079602f4922603c613f572caa8bd4c174b69/packages/indexer/src/api/endpoints/collections/get-collections/v7.ts#L739 is it fine to leave it as is or should I still change it?

2024-03-12 17:48 UTC, JadenDurnford commented on packages/indexer/src/api/endpoints/tokens/get-user-tokens/v10.ts
> +                tokenCount: String(r.collection_token_count),
Yup, it is done like that on the collections api https://github.com/reservoirprotocol/indexer/blob/de3a079602f4922603c613f572caa8bd4c174b69/packages/indexer/src/api/endpoints/collections/get-collections/v7.ts#L854

2024-03-13 17:40 UTC, nofir approved these changes

2024-03-14 17:42 UTC, merged